namespace QuanLyCongTyDone
{
	partial class Account
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Account));
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
			dtgac = new Bunifu.UI.WinForms.BunifuDataGridView();
			lbidun = new Bunifu.UI.WinForms.BunifuLabel();
			btthem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			tbid1 = new Bunifu.UI.WinForms.BunifuTextBox();
			btSua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btclear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			tbus2 = new Bunifu.UI.WinForms.BunifuTextBox();
			lbUn = new Bunifu.UI.WinForms.BunifuLabel();
			tbpw3 = new Bunifu.UI.WinForms.BunifuTextBox();
			lbpw = new Bunifu.UI.WinForms.BunifuLabel();
			lbrole = new Bunifu.UI.WinForms.BunifuLabel();
			cbrole2 = new ComboBox();
			bunifuGroupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)dtgac).BeginInit();
			SuspendLayout();
			// 
			// bunifuGroupBox1
			// 
			bunifuGroupBox1.BorderColor = Color.LightGray;
			bunifuGroupBox1.BorderRadius = 1;
			bunifuGroupBox1.BorderThickness = 1;
			bunifuGroupBox1.Controls.Add(dtgac);
			bunifuGroupBox1.Font = new Font("Segoe UI", 9F);
			bunifuGroupBox1.LabelAlign = HorizontalAlignment.Left;
			bunifuGroupBox1.LabelIndent = 10;
			bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
			bunifuGroupBox1.Location = new Point(18, 17);
			bunifuGroupBox1.Name = "bunifuGroupBox1";
			bunifuGroupBox1.Size = new Size(764, 206);
			bunifuGroupBox1.TabIndex = 0;
			bunifuGroupBox1.TabStop = false;
			bunifuGroupBox1.Text = "Tài Khoản";
			// 
			// dtgac
			// 
			dtgac.AllowCustomTheming = false;
			dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
			dataGridViewCellStyle1.ForeColor = Color.Black;
			dtgac.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			dtgac.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			dtgac.BorderStyle = BorderStyle.None;
			dtgac.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
			dtgac.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
			dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = Color.White;
			dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dataGridViewCellStyle2.SelectionForeColor = Color.White;
			dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
			dtgac.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			dtgac.ColumnHeadersHeight = 40;
			dtgac.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
			dtgac.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgac.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
			dtgac.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgac.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
			dtgac.CurrentTheme.BackColor = Color.White;
			dtgac.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
			dtgac.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
			dtgac.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dtgac.CurrentTheme.HeaderStyle.ForeColor = Color.White;
			dtgac.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dtgac.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
			dtgac.CurrentTheme.Name = null;
			dtgac.CurrentTheme.RowsStyle.BackColor = Color.White;
			dtgac.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgac.CurrentTheme.RowsStyle.ForeColor = Color.Black;
			dtgac.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgac.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = Color.White;
			dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dataGridViewCellStyle3.ForeColor = Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dataGridViewCellStyle3.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
			dtgac.DefaultCellStyle = dataGridViewCellStyle3;
			dtgac.EnableHeadersVisualStyles = false;
			dtgac.GridColor = Color.FromArgb(221, 238, 255);
			dtgac.HeaderBackColor = Color.DodgerBlue;
			dtgac.HeaderBgColor = Color.Empty;
			dtgac.HeaderForeColor = Color.White;
			dtgac.Location = new Point(23, 32);
			dtgac.Name = "dtgac";
			dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = SystemColors.Control;
			dataGridViewCellStyle4.Font = new Font("Segoe UI", 9F);
			dataGridViewCellStyle4.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle4.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle4.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle4.WrapMode = DataGridViewTriState.True;
			dtgac.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
			dtgac.RowHeadersVisible = false;
			dtgac.RowHeadersWidth = 51;
			dtgac.RowTemplate.Height = 40;
			dtgac.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			dtgac.Size = new Size(715, 154);
			dtgac.TabIndex = 0;
			dtgac.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
			dtgac.CellContentClick += dtgac_CellContentClick;
			// 
			// lbidun
			// 
			lbidun.AllowParentOverrides = false;
			lbidun.AutoEllipsis = false;
			lbidun.CursorType = Cursors.Default;
			lbidun.Font = new Font("Segoe UI", 15F);
			lbidun.Location = new Point(46, 238);
			lbidun.Name = "lbidun";
			lbidun.RightToLeft = RightToLeft.No;
			lbidun.Size = new Size(25, 35);
			lbidun.TabIndex = 1;
			lbidun.Text = "ID";
			lbidun.TextAlignment = ContentAlignment.TopLeft;
			lbidun.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// btthem
			// 
			btthem.AllowAnimations = true;
			btthem.AllowMouseEffects = true;
			btthem.AllowToggling = false;
			btthem.AnimationSpeed = 200;
			btthem.AutoGenerateColors = false;
			btthem.AutoRoundBorders = false;
			btthem.AutoSizeLeftIcon = true;
			btthem.AutoSizeRightIcon = true;
			btthem.BackColor = Color.Transparent;
			btthem.BackColor1 = Color.FromArgb(51, 122, 183);
			btthem.BackgroundImage = (Image)resources.GetObject("btthem.BackgroundImage");
			btthem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.ButtonText = "Thêm";
			btthem.ButtonTextMarginLeft = 0;
			btthem.ColorContrastOnClick = 45;
			btthem.ColorContrastOnHover = 45;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			btthem.CustomizableEdges = borderEdges1;
			btthem.DialogResult = DialogResult.None;
			btthem.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btthem.DisabledFillColor = Color.Empty;
			btthem.DisabledForecolor = Color.Empty;
			btthem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btthem.Font = new Font("Segoe UI", 9F);
			btthem.ForeColor = Color.White;
			btthem.IconLeft = null;
			btthem.IconLeftAlign = ContentAlignment.MiddleLeft;
			btthem.IconLeftCursor = Cursors.Default;
			btthem.IconLeftPadding = new Padding(11, 3, 3, 3);
			btthem.IconMarginLeft = 11;
			btthem.IconPadding = 10;
			btthem.IconRight = null;
			btthem.IconRightAlign = ContentAlignment.MiddleRight;
			btthem.IconRightCursor = Cursors.Default;
			btthem.IconRightPadding = new Padding(3, 3, 7, 3);
			btthem.IconSize = 25;
			btthem.IdleBorderColor = Color.Empty;
			btthem.IdleBorderRadius = 0;
			btthem.IdleBorderThickness = 0;
			btthem.IdleFillColor = Color.Empty;
			btthem.IdleIconLeftImage = null;
			btthem.IdleIconRightImage = null;
			btthem.IndicateFocus = false;
			btthem.Location = new Point(18, 366);
			btthem.Name = "btthem";
			btthem.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btthem.OnDisabledState.BorderRadius = 1;
			btthem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnDisabledState.BorderThickness = 1;
			btthem.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btthem.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btthem.OnDisabledState.IconLeftImage = null;
			btthem.OnDisabledState.IconRightImage = null;
			btthem.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btthem.onHoverState.BorderRadius = 1;
			btthem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.onHoverState.BorderThickness = 1;
			btthem.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btthem.onHoverState.ForeColor = Color.White;
			btthem.onHoverState.IconLeftImage = null;
			btthem.onHoverState.IconRightImage = null;
			btthem.OnIdleState.BorderColor = Color.DodgerBlue;
			btthem.OnIdleState.BorderRadius = 1;
			btthem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnIdleState.BorderThickness = 1;
			btthem.OnIdleState.FillColor = Color.DodgerBlue;
			btthem.OnIdleState.ForeColor = Color.White;
			btthem.OnIdleState.IconLeftImage = null;
			btthem.OnIdleState.IconRightImage = null;
			btthem.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btthem.OnPressedState.BorderRadius = 1;
			btthem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnPressedState.BorderThickness = 1;
			btthem.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btthem.OnPressedState.ForeColor = Color.White;
			btthem.OnPressedState.IconLeftImage = null;
			btthem.OnPressedState.IconRightImage = null;
			btthem.Size = new Size(121, 36);
			btthem.TabIndex = 2;
			btthem.TextAlign = ContentAlignment.MiddleCenter;
			btthem.TextAlignment = HorizontalAlignment.Center;
			btthem.TextMarginLeft = 0;
			btthem.TextPadding = new Padding(0);
			btthem.UseDefaultRadiusAndThickness = true;
			btthem.Click += btthem_Click;
			// 
			// tbid1
			// 
			tbid1.AcceptsReturn = false;
			tbid1.AcceptsTab = false;
			tbid1.AnimationSpeed = 200;
			tbid1.AutoCompleteMode = AutoCompleteMode.None;
			tbid1.AutoCompleteSource = AutoCompleteSource.None;
			tbid1.AutoSizeHeight = true;
			tbid1.BackColor = Color.Transparent;
			tbid1.BackgroundImage = (Image)resources.GetObject("tbid1.BackgroundImage");
			tbid1.BorderColorActive = Color.DodgerBlue;
			tbid1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbid1.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbid1.BorderColorIdle = Color.Silver;
			tbid1.BorderRadius = 1;
			tbid1.BorderThickness = 1;
			tbid1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbid1.CharacterCasing = CharacterCasing.Normal;
			tbid1.DefaultFont = new Font("Segoe UI", 9.25F);
			tbid1.DefaultText = "";
			tbid1.FillColor = Color.White;
			tbid1.HideSelection = true;
			tbid1.IconLeft = null;
			tbid1.IconLeftCursor = Cursors.IBeam;
			tbid1.IconPadding = 10;
			tbid1.IconRight = null;
			tbid1.IconRightCursor = Cursors.IBeam;
			tbid1.Location = new Point(178, 244);
			tbid1.MaxLength = 32767;
			tbid1.MinimumSize = new Size(1, 1);
			tbid1.Modified = false;
			tbid1.Multiline = false;
			tbid1.Name = "tbid1";
			stateProperties1.BorderColor = Color.DodgerBlue;
			stateProperties1.FillColor = Color.Empty;
			stateProperties1.ForeColor = Color.Empty;
			stateProperties1.PlaceholderForeColor = Color.Empty;
			tbid1.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties2.PlaceholderForeColor = Color.DarkGray;
			tbid1.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties3.FillColor = Color.Empty;
			stateProperties3.ForeColor = Color.Empty;
			stateProperties3.PlaceholderForeColor = Color.Empty;
			tbid1.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = Color.Silver;
			stateProperties4.FillColor = Color.White;
			stateProperties4.ForeColor = Color.Empty;
			stateProperties4.PlaceholderForeColor = Color.Empty;
			tbid1.OnIdleState = stateProperties4;
			tbid1.Padding = new Padding(3);
			tbid1.PasswordChar = '\0';
			tbid1.PlaceholderForeColor = Color.Silver;
			tbid1.PlaceholderText = "Enter text";
			tbid1.ReadOnly = false;
			tbid1.ScrollBars = ScrollBars.None;
			tbid1.SelectedText = "";
			tbid1.SelectionLength = 0;
			tbid1.SelectionStart = 0;
			tbid1.ShortcutsEnabled = true;
			tbid1.Size = new Size(149, 29);
			tbid1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbid1.TabIndex = 3;
			tbid1.TextAlign = HorizontalAlignment.Left;
			tbid1.TextMarginBottom = 0;
			tbid1.TextMarginLeft = 3;
			tbid1.TextMarginTop = 1;
			tbid1.TextPlaceholder = "Enter text";
			tbid1.UseSystemPasswordChar = false;
			tbid1.WordWrap = true;
			// 
			// btSua
			// 
			btSua.AllowAnimations = true;
			btSua.AllowMouseEffects = true;
			btSua.AllowToggling = false;
			btSua.AnimationSpeed = 200;
			btSua.AutoGenerateColors = false;
			btSua.AutoRoundBorders = false;
			btSua.AutoSizeLeftIcon = true;
			btSua.AutoSizeRightIcon = true;
			btSua.BackColor = Color.Transparent;
			btSua.BackColor1 = Color.FromArgb(51, 122, 183);
			btSua.BackgroundImage = (Image)resources.GetObject("btSua.BackgroundImage");
			btSua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btSua.ButtonText = "Sửa";
			btSua.ButtonTextMarginLeft = 0;
			btSua.ColorContrastOnClick = 45;
			btSua.ColorContrastOnHover = 45;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			btSua.CustomizableEdges = borderEdges2;
			btSua.DialogResult = DialogResult.None;
			btSua.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btSua.DisabledFillColor = Color.Empty;
			btSua.DisabledForecolor = Color.Empty;
			btSua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btSua.Font = new Font("Segoe UI", 9F);
			btSua.ForeColor = Color.White;
			btSua.IconLeft = null;
			btSua.IconLeftAlign = ContentAlignment.MiddleLeft;
			btSua.IconLeftCursor = Cursors.Default;
			btSua.IconLeftPadding = new Padding(11, 3, 3, 3);
			btSua.IconMarginLeft = 11;
			btSua.IconPadding = 10;
			btSua.IconRight = null;
			btSua.IconRightAlign = ContentAlignment.MiddleRight;
			btSua.IconRightCursor = Cursors.Default;
			btSua.IconRightPadding = new Padding(3, 3, 7, 3);
			btSua.IconSize = 25;
			btSua.IdleBorderColor = Color.Empty;
			btSua.IdleBorderRadius = 0;
			btSua.IdleBorderThickness = 0;
			btSua.IdleFillColor = Color.Empty;
			btSua.IdleIconLeftImage = null;
			btSua.IdleIconRightImage = null;
			btSua.IndicateFocus = false;
			btSua.Location = new Point(178, 366);
			btSua.Name = "btSua";
			btSua.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btSua.OnDisabledState.BorderRadius = 1;
			btSua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btSua.OnDisabledState.BorderThickness = 1;
			btSua.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btSua.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btSua.OnDisabledState.IconLeftImage = null;
			btSua.OnDisabledState.IconRightImage = null;
			btSua.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btSua.onHoverState.BorderRadius = 1;
			btSua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btSua.onHoverState.BorderThickness = 1;
			btSua.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btSua.onHoverState.ForeColor = Color.White;
			btSua.onHoverState.IconLeftImage = null;
			btSua.onHoverState.IconRightImage = null;
			btSua.OnIdleState.BorderColor = Color.DodgerBlue;
			btSua.OnIdleState.BorderRadius = 1;
			btSua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btSua.OnIdleState.BorderThickness = 1;
			btSua.OnIdleState.FillColor = Color.DodgerBlue;
			btSua.OnIdleState.ForeColor = Color.White;
			btSua.OnIdleState.IconLeftImage = null;
			btSua.OnIdleState.IconRightImage = null;
			btSua.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btSua.OnPressedState.BorderRadius = 1;
			btSua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btSua.OnPressedState.BorderThickness = 1;
			btSua.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btSua.OnPressedState.ForeColor = Color.White;
			btSua.OnPressedState.IconLeftImage = null;
			btSua.OnPressedState.IconRightImage = null;
			btSua.Size = new Size(121, 36);
			btSua.TabIndex = 4;
			btSua.TextAlign = ContentAlignment.MiddleCenter;
			btSua.TextAlignment = HorizontalAlignment.Center;
			btSua.TextMarginLeft = 0;
			btSua.TextPadding = new Padding(0);
			btSua.UseDefaultRadiusAndThickness = true;
			btSua.Click += btSua_Click;
			// 
			// btXoa
			// 
			btXoa.AllowAnimations = true;
			btXoa.AllowMouseEffects = true;
			btXoa.AllowToggling = false;
			btXoa.AnimationSpeed = 200;
			btXoa.AutoGenerateColors = false;
			btXoa.AutoRoundBorders = false;
			btXoa.AutoSizeLeftIcon = true;
			btXoa.AutoSizeRightIcon = true;
			btXoa.BackColor = Color.Transparent;
			btXoa.BackColor1 = Color.FromArgb(51, 122, 183);
			btXoa.BackgroundImage = (Image)resources.GetObject("btXoa.BackgroundImage");
			btXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btXoa.ButtonText = "Xóa";
			btXoa.ButtonTextMarginLeft = 0;
			btXoa.ColorContrastOnClick = 45;
			btXoa.ColorContrastOnHover = 45;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			btXoa.CustomizableEdges = borderEdges3;
			btXoa.DialogResult = DialogResult.None;
			btXoa.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btXoa.DisabledFillColor = Color.Empty;
			btXoa.DisabledForecolor = Color.Empty;
			btXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btXoa.Font = new Font("Segoe UI", 9F);
			btXoa.ForeColor = Color.White;
			btXoa.IconLeft = null;
			btXoa.IconLeftAlign = ContentAlignment.MiddleLeft;
			btXoa.IconLeftCursor = Cursors.Default;
			btXoa.IconLeftPadding = new Padding(11, 3, 3, 3);
			btXoa.IconMarginLeft = 11;
			btXoa.IconPadding = 10;
			btXoa.IconRight = null;
			btXoa.IconRightAlign = ContentAlignment.MiddleRight;
			btXoa.IconRightCursor = Cursors.Default;
			btXoa.IconRightPadding = new Padding(3, 3, 7, 3);
			btXoa.IconSize = 25;
			btXoa.IdleBorderColor = Color.Empty;
			btXoa.IdleBorderRadius = 0;
			btXoa.IdleBorderThickness = 0;
			btXoa.IdleFillColor = Color.Empty;
			btXoa.IdleIconLeftImage = null;
			btXoa.IdleIconRightImage = null;
			btXoa.IndicateFocus = false;
			btXoa.Location = new Point(339, 366);
			btXoa.Name = "btXoa";
			btXoa.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btXoa.OnDisabledState.BorderRadius = 1;
			btXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btXoa.OnDisabledState.BorderThickness = 1;
			btXoa.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btXoa.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btXoa.OnDisabledState.IconLeftImage = null;
			btXoa.OnDisabledState.IconRightImage = null;
			btXoa.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btXoa.onHoverState.BorderRadius = 1;
			btXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btXoa.onHoverState.BorderThickness = 1;
			btXoa.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btXoa.onHoverState.ForeColor = Color.White;
			btXoa.onHoverState.IconLeftImage = null;
			btXoa.onHoverState.IconRightImage = null;
			btXoa.OnIdleState.BorderColor = Color.DodgerBlue;
			btXoa.OnIdleState.BorderRadius = 1;
			btXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btXoa.OnIdleState.BorderThickness = 1;
			btXoa.OnIdleState.FillColor = Color.DodgerBlue;
			btXoa.OnIdleState.ForeColor = Color.White;
			btXoa.OnIdleState.IconLeftImage = null;
			btXoa.OnIdleState.IconRightImage = null;
			btXoa.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btXoa.OnPressedState.BorderRadius = 1;
			btXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btXoa.OnPressedState.BorderThickness = 1;
			btXoa.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btXoa.OnPressedState.ForeColor = Color.White;
			btXoa.OnPressedState.IconLeftImage = null;
			btXoa.OnPressedState.IconRightImage = null;
			btXoa.Size = new Size(121, 36);
			btXoa.TabIndex = 5;
			btXoa.TextAlign = ContentAlignment.MiddleCenter;
			btXoa.TextAlignment = HorizontalAlignment.Center;
			btXoa.TextMarginLeft = 0;
			btXoa.TextPadding = new Padding(0);
			btXoa.UseDefaultRadiusAndThickness = true;
			btXoa.Click += btXoa_Click;
			// 
			// btclear
			// 
			btclear.AllowAnimations = true;
			btclear.AllowMouseEffects = true;
			btclear.AllowToggling = false;
			btclear.AnimationSpeed = 200;
			btclear.AutoGenerateColors = false;
			btclear.AutoRoundBorders = false;
			btclear.AutoSizeLeftIcon = true;
			btclear.AutoSizeRightIcon = true;
			btclear.BackColor = Color.Transparent;
			btclear.BackColor1 = Color.FromArgb(51, 122, 183);
			btclear.BackgroundImage = (Image)resources.GetObject("btclear.BackgroundImage");
			btclear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.ButtonText = "Clear";
			btclear.ButtonTextMarginLeft = 0;
			btclear.ColorContrastOnClick = 45;
			btclear.ColorContrastOnHover = 45;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			btclear.CustomizableEdges = borderEdges4;
			btclear.DialogResult = DialogResult.None;
			btclear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btclear.DisabledFillColor = Color.Empty;
			btclear.DisabledForecolor = Color.Empty;
			btclear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btclear.Font = new Font("Segoe UI", 9F);
			btclear.ForeColor = Color.White;
			btclear.IconLeft = null;
			btclear.IconLeftAlign = ContentAlignment.MiddleLeft;
			btclear.IconLeftCursor = Cursors.Default;
			btclear.IconLeftPadding = new Padding(11, 3, 3, 3);
			btclear.IconMarginLeft = 11;
			btclear.IconPadding = 10;
			btclear.IconRight = null;
			btclear.IconRightAlign = ContentAlignment.MiddleRight;
			btclear.IconRightCursor = Cursors.Default;
			btclear.IconRightPadding = new Padding(3, 3, 7, 3);
			btclear.IconSize = 25;
			btclear.IdleBorderColor = Color.Empty;
			btclear.IdleBorderRadius = 0;
			btclear.IdleBorderThickness = 0;
			btclear.IdleFillColor = Color.Empty;
			btclear.IdleIconLeftImage = null;
			btclear.IdleIconRightImage = null;
			btclear.IndicateFocus = false;
			btclear.Location = new Point(502, 366);
			btclear.Name = "btclear";
			btclear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btclear.OnDisabledState.BorderRadius = 1;
			btclear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnDisabledState.BorderThickness = 1;
			btclear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btclear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btclear.OnDisabledState.IconLeftImage = null;
			btclear.OnDisabledState.IconRightImage = null;
			btclear.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btclear.onHoverState.BorderRadius = 1;
			btclear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.onHoverState.BorderThickness = 1;
			btclear.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btclear.onHoverState.ForeColor = Color.White;
			btclear.onHoverState.IconLeftImage = null;
			btclear.onHoverState.IconRightImage = null;
			btclear.OnIdleState.BorderColor = Color.DodgerBlue;
			btclear.OnIdleState.BorderRadius = 1;
			btclear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnIdleState.BorderThickness = 1;
			btclear.OnIdleState.FillColor = Color.DodgerBlue;
			btclear.OnIdleState.ForeColor = Color.White;
			btclear.OnIdleState.IconLeftImage = null;
			btclear.OnIdleState.IconRightImage = null;
			btclear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btclear.OnPressedState.BorderRadius = 1;
			btclear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnPressedState.BorderThickness = 1;
			btclear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btclear.OnPressedState.ForeColor = Color.White;
			btclear.OnPressedState.IconLeftImage = null;
			btclear.OnPressedState.IconRightImage = null;
			btclear.Size = new Size(121, 36);
			btclear.TabIndex = 6;
			btclear.TextAlign = ContentAlignment.MiddleCenter;
			btclear.TextAlignment = HorizontalAlignment.Center;
			btclear.TextMarginLeft = 0;
			btclear.TextPadding = new Padding(0);
			btclear.UseDefaultRadiusAndThickness = true;
			btclear.Click += btclear_Click;
			// 
			// bunifuButton5
			// 
			bunifuButton5.AllowAnimations = true;
			bunifuButton5.AllowMouseEffects = true;
			bunifuButton5.AllowToggling = false;
			bunifuButton5.AnimationSpeed = 200;
			bunifuButton5.AutoGenerateColors = false;
			bunifuButton5.AutoRoundBorders = false;
			bunifuButton5.AutoSizeLeftIcon = true;
			bunifuButton5.AutoSizeRightIcon = true;
			bunifuButton5.BackColor = Color.Transparent;
			bunifuButton5.BackColor1 = Color.FromArgb(51, 122, 183);
			bunifuButton5.BackgroundImage = (Image)resources.GetObject("bunifuButton5.BackgroundImage");
			bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.ButtonText = "Home";
			bunifuButton5.ButtonTextMarginLeft = 0;
			bunifuButton5.ColorContrastOnClick = 45;
			bunifuButton5.ColorContrastOnHover = 45;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			bunifuButton5.CustomizableEdges = borderEdges5;
			bunifuButton5.DialogResult = DialogResult.None;
			bunifuButton5.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.DisabledFillColor = Color.Empty;
			bunifuButton5.DisabledForecolor = Color.Empty;
			bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			bunifuButton5.Font = new Font("Segoe UI", 9F);
			bunifuButton5.ForeColor = Color.White;
			bunifuButton5.IconLeft = null;
			bunifuButton5.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton5.IconLeftCursor = Cursors.Default;
			bunifuButton5.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton5.IconMarginLeft = 11;
			bunifuButton5.IconPadding = 10;
			bunifuButton5.IconRight = null;
			bunifuButton5.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton5.IconRightCursor = Cursors.Default;
			bunifuButton5.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton5.IconSize = 25;
			bunifuButton5.IdleBorderColor = Color.Empty;
			bunifuButton5.IdleBorderRadius = 0;
			bunifuButton5.IdleBorderThickness = 0;
			bunifuButton5.IdleFillColor = Color.Empty;
			bunifuButton5.IdleIconLeftImage = null;
			bunifuButton5.IdleIconRightImage = null;
			bunifuButton5.IndicateFocus = false;
			bunifuButton5.Location = new Point(661, 366);
			bunifuButton5.Name = "bunifuButton5";
			bunifuButton5.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.OnDisabledState.BorderRadius = 1;
			bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnDisabledState.BorderThickness = 1;
			bunifuButton5.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton5.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton5.OnDisabledState.IconLeftImage = null;
			bunifuButton5.OnDisabledState.IconRightImage = null;
			bunifuButton5.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.BorderRadius = 1;
			bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.onHoverState.BorderThickness = 1;
			bunifuButton5.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.ForeColor = Color.White;
			bunifuButton5.onHoverState.IconLeftImage = null;
			bunifuButton5.onHoverState.IconRightImage = null;
			bunifuButton5.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.BorderRadius = 1;
			bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnIdleState.BorderThickness = 1;
			bunifuButton5.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.ForeColor = Color.White;
			bunifuButton5.OnIdleState.IconLeftImage = null;
			bunifuButton5.OnIdleState.IconRightImage = null;
			bunifuButton5.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.BorderRadius = 1;
			bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnPressedState.BorderThickness = 1;
			bunifuButton5.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.ForeColor = Color.White;
			bunifuButton5.OnPressedState.IconLeftImage = null;
			bunifuButton5.OnPressedState.IconRightImage = null;
			bunifuButton5.Size = new Size(121, 36);
			bunifuButton5.TabIndex = 7;
			bunifuButton5.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton5.TextAlignment = HorizontalAlignment.Center;
			bunifuButton5.TextMarginLeft = 0;
			bunifuButton5.TextPadding = new Padding(0);
			bunifuButton5.UseDefaultRadiusAndThickness = true;
			bunifuButton5.Click += bunifuButton5_Click;
			// 
			// tbus2
			// 
			tbus2.AcceptsReturn = false;
			tbus2.AcceptsTab = false;
			tbus2.AnimationSpeed = 200;
			tbus2.AutoCompleteMode = AutoCompleteMode.None;
			tbus2.AutoCompleteSource = AutoCompleteSource.None;
			tbus2.AutoSizeHeight = true;
			tbus2.BackColor = Color.Transparent;
			tbus2.BackgroundImage = (Image)resources.GetObject("tbus2.BackgroundImage");
			tbus2.BorderColorActive = Color.DodgerBlue;
			tbus2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbus2.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbus2.BorderColorIdle = Color.Silver;
			tbus2.BorderRadius = 1;
			tbus2.BorderThickness = 1;
			tbus2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbus2.CharacterCasing = CharacterCasing.Normal;
			tbus2.DefaultFont = new Font("Segoe UI", 9.25F);
			tbus2.DefaultText = "";
			tbus2.FillColor = Color.White;
			tbus2.HideSelection = true;
			tbus2.IconLeft = null;
			tbus2.IconLeftCursor = Cursors.IBeam;
			tbus2.IconPadding = 10;
			tbus2.IconRight = null;
			tbus2.IconRightCursor = Cursors.IBeam;
			tbus2.Location = new Point(554, 244);
			tbus2.MaxLength = 32767;
			tbus2.MinimumSize = new Size(1, 1);
			tbus2.Modified = false;
			tbus2.Multiline = false;
			tbus2.Name = "tbus2";
			stateProperties5.BorderColor = Color.DodgerBlue;
			stateProperties5.FillColor = Color.Empty;
			stateProperties5.ForeColor = Color.Empty;
			stateProperties5.PlaceholderForeColor = Color.Empty;
			tbus2.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties6.PlaceholderForeColor = Color.DarkGray;
			tbus2.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties7.FillColor = Color.Empty;
			stateProperties7.ForeColor = Color.Empty;
			stateProperties7.PlaceholderForeColor = Color.Empty;
			tbus2.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = Color.Silver;
			stateProperties8.FillColor = Color.White;
			stateProperties8.ForeColor = Color.Empty;
			stateProperties8.PlaceholderForeColor = Color.Empty;
			tbus2.OnIdleState = stateProperties8;
			tbus2.Padding = new Padding(3);
			tbus2.PasswordChar = '\0';
			tbus2.PlaceholderForeColor = Color.Silver;
			tbus2.PlaceholderText = "Enter text";
			tbus2.ReadOnly = false;
			tbus2.ScrollBars = ScrollBars.None;
			tbus2.SelectedText = "";
			tbus2.SelectionLength = 0;
			tbus2.SelectionStart = 0;
			tbus2.ShortcutsEnabled = true;
			tbus2.Size = new Size(149, 29);
			tbus2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbus2.TabIndex = 9;
			tbus2.TextAlign = HorizontalAlignment.Left;
			tbus2.TextMarginBottom = 0;
			tbus2.TextMarginLeft = 3;
			tbus2.TextMarginTop = 1;
			tbus2.TextPlaceholder = "Enter text";
			tbus2.UseSystemPasswordChar = false;
			tbus2.WordWrap = true;
			// 
			// lbUn
			// 
			lbUn.AllowParentOverrides = false;
			lbUn.AutoEllipsis = false;
			lbUn.CursorType = Cursors.Default;
			lbUn.Font = new Font("Segoe UI", 15F);
			lbUn.Location = new Point(417, 238);
			lbUn.Name = "lbUn";
			lbUn.RightToLeft = RightToLeft.No;
			lbUn.Size = new Size(112, 35);
			lbUn.TabIndex = 8;
			lbUn.Text = "Username";
			lbUn.TextAlignment = ContentAlignment.TopLeft;
			lbUn.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbpw3
			// 
			tbpw3.AcceptsReturn = false;
			tbpw3.AcceptsTab = false;
			tbpw3.AnimationSpeed = 200;
			tbpw3.AutoCompleteMode = AutoCompleteMode.None;
			tbpw3.AutoCompleteSource = AutoCompleteSource.None;
			tbpw3.AutoSizeHeight = true;
			tbpw3.BackColor = Color.Transparent;
			tbpw3.BackgroundImage = (Image)resources.GetObject("tbpw3.BackgroundImage");
			tbpw3.BorderColorActive = Color.DodgerBlue;
			tbpw3.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbpw3.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbpw3.BorderColorIdle = Color.Silver;
			tbpw3.BorderRadius = 1;
			tbpw3.BorderThickness = 1;
			tbpw3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbpw3.CharacterCasing = CharacterCasing.Normal;
			tbpw3.DefaultFont = new Font("Segoe UI", 9.25F);
			tbpw3.DefaultText = "";
			tbpw3.FillColor = Color.White;
			tbpw3.HideSelection = true;
			tbpw3.IconLeft = null;
			tbpw3.IconLeftCursor = Cursors.IBeam;
			tbpw3.IconPadding = 10;
			tbpw3.IconRight = null;
			tbpw3.IconRightCursor = Cursors.IBeam;
			tbpw3.Location = new Point(554, 298);
			tbpw3.MaxLength = 32767;
			tbpw3.MinimumSize = new Size(1, 1);
			tbpw3.Modified = false;
			tbpw3.Multiline = false;
			tbpw3.Name = "tbpw3";
			stateProperties9.BorderColor = Color.DodgerBlue;
			stateProperties9.FillColor = Color.Empty;
			stateProperties9.ForeColor = Color.Empty;
			stateProperties9.PlaceholderForeColor = Color.Empty;
			tbpw3.OnActiveState = stateProperties9;
			stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties10.PlaceholderForeColor = Color.DarkGray;
			tbpw3.OnDisabledState = stateProperties10;
			stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties11.FillColor = Color.Empty;
			stateProperties11.ForeColor = Color.Empty;
			stateProperties11.PlaceholderForeColor = Color.Empty;
			tbpw3.OnHoverState = stateProperties11;
			stateProperties12.BorderColor = Color.Silver;
			stateProperties12.FillColor = Color.White;
			stateProperties12.ForeColor = Color.Empty;
			stateProperties12.PlaceholderForeColor = Color.Empty;
			tbpw3.OnIdleState = stateProperties12;
			tbpw3.Padding = new Padding(3);
			tbpw3.PasswordChar = '\0';
			tbpw3.PlaceholderForeColor = Color.Silver;
			tbpw3.PlaceholderText = "Enter text";
			tbpw3.ReadOnly = false;
			tbpw3.ScrollBars = ScrollBars.None;
			tbpw3.SelectedText = "";
			tbpw3.SelectionLength = 0;
			tbpw3.SelectionStart = 0;
			tbpw3.ShortcutsEnabled = true;
			tbpw3.Size = new Size(149, 29);
			tbpw3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbpw3.TabIndex = 11;
			tbpw3.TextAlign = HorizontalAlignment.Left;
			tbpw3.TextMarginBottom = 0;
			tbpw3.TextMarginLeft = 3;
			tbpw3.TextMarginTop = 1;
			tbpw3.TextPlaceholder = "Enter text";
			tbpw3.UseSystemPasswordChar = false;
			tbpw3.WordWrap = true;
			// 
			// lbpw
			// 
			lbpw.AllowParentOverrides = false;
			lbpw.AutoEllipsis = false;
			lbpw.CursorType = Cursors.Default;
			lbpw.Font = new Font("Segoe UI", 15F);
			lbpw.Location = new Point(417, 292);
			lbpw.Name = "lbpw";
			lbpw.RightToLeft = RightToLeft.No;
			lbpw.Size = new Size(106, 35);
			lbpw.TabIndex = 10;
			lbpw.Text = "Password";
			lbpw.TextAlignment = ContentAlignment.TopLeft;
			lbpw.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// lbrole
			// 
			lbrole.AllowParentOverrides = false;
			lbrole.AutoEllipsis = false;
			lbrole.CursorType = Cursors.Default;
			lbrole.Font = new Font("Segoe UI", 15F);
			lbrole.Location = new Point(46, 292);
			lbrole.Name = "lbrole";
			lbrole.RightToLeft = RightToLeft.No;
			lbrole.Size = new Size(49, 35);
			lbrole.TabIndex = 12;
			lbrole.Text = "Role";
			lbrole.TextAlignment = ContentAlignment.TopLeft;
			lbrole.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// cbrole2
			// 
			cbrole2.FormattingEnabled = true;
			cbrole2.Location = new Point(178, 297);
			cbrole2.Name = "cbrole2";
			cbrole2.Size = new Size(149, 28);
			cbrole2.TabIndex = 13;
			cbrole2.KeyDown += cbrole2_KeyDown;
			cbrole2.KeyPress += cbrole2_KeyPress;
			// 
			// Account
			// 
			AutoScaleDimensions = new SizeF(8F, 20F);
			AutoScaleMode = AutoScaleMode.Font;
			ClientSize = new Size(800, 450);
			Controls.Add(cbrole2);
			Controls.Add(lbrole);
			Controls.Add(tbpw3);
			Controls.Add(lbpw);
			Controls.Add(tbus2);
			Controls.Add(lbUn);
			Controls.Add(bunifuButton5);
			Controls.Add(btclear);
			Controls.Add(btXoa);
			Controls.Add(btSua);
			Controls.Add(tbid1);
			Controls.Add(btthem);
			Controls.Add(lbidun);
			Controls.Add(bunifuGroupBox1);
			Name = "Account";
			Text = "Account";
			Load += Account_Load;
			bunifuGroupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)dtgac).EndInit();
			ResumeLayout(false);
			PerformLayout();
		}

		#endregion

		private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
		private Bunifu.UI.WinForms.BunifuDataGridView dtgac;
		private Bunifu.UI.WinForms.BunifuLabel lbidun;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btthem;
		private Bunifu.UI.WinForms.BunifuTextBox tbid1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btSua;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btXoa;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btclear;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
		private Bunifu.UI.WinForms.BunifuTextBox tbus2;
		private Bunifu.UI.WinForms.BunifuLabel lbUn;
		private Bunifu.UI.WinForms.BunifuTextBox tbpw3;
		private Bunifu.UI.WinForms.BunifuLabel lbpw;
		private Bunifu.UI.WinForms.BunifuLabel lbrole;
		private ComboBox cbrole2;
	}
}