namespace QuanLyCongTyDone
{
	partial class DeAn
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			DataGridViewCellStyle dataGridViewCellStyle5 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle6 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle7 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle8 = new DataGridViewCellStyle();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DeAn));
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
			dtgda = new Bunifu.UI.WinForms.BunifuDataGridView();
			tbmada = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
			btthem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btsua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btxoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btclear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
			tbtenda = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuGroupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)dtgda).BeginInit();
			SuspendLayout();
			// 
			// bunifuGroupBox1
			// 
			bunifuGroupBox1.BorderColor = Color.LightGray;
			bunifuGroupBox1.BorderRadius = 1;
			bunifuGroupBox1.BorderThickness = 1;
			bunifuGroupBox1.Controls.Add(dtgda);
			bunifuGroupBox1.Font = new Font("Segoe UI", 9F);
			bunifuGroupBox1.LabelAlign = HorizontalAlignment.Left;
			bunifuGroupBox1.LabelIndent = 10;
			bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
			bunifuGroupBox1.Location = new Point(27, 22);
			bunifuGroupBox1.Name = "bunifuGroupBox1";
			bunifuGroupBox1.Size = new Size(727, 197);
			bunifuGroupBox1.TabIndex = 0;
			bunifuGroupBox1.TabStop = false;
			bunifuGroupBox1.Text = "Đề Án";
			// 
			// dtgda
			// 
			dtgda.AllowCustomTheming = false;
			dataGridViewCellStyle5.BackColor = Color.FromArgb(248, 251, 255);
			dataGridViewCellStyle5.ForeColor = Color.Black;
			dtgda.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle5;
			dtgda.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			dtgda.BorderStyle = BorderStyle.None;
			dtgda.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
			dtgda.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle6.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = Color.DodgerBlue;
			dataGridViewCellStyle6.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dataGridViewCellStyle6.ForeColor = Color.White;
			dataGridViewCellStyle6.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dataGridViewCellStyle6.SelectionForeColor = Color.White;
			dataGridViewCellStyle6.WrapMode = DataGridViewTriState.True;
			dtgda.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle6;
			dtgda.ColumnHeadersHeight = 40;
			dtgda.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
			dtgda.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgda.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
			dtgda.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgda.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
			dtgda.CurrentTheme.BackColor = Color.White;
			dtgda.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
			dtgda.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
			dtgda.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dtgda.CurrentTheme.HeaderStyle.ForeColor = Color.White;
			dtgda.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dtgda.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
			dtgda.CurrentTheme.Name = null;
			dtgda.CurrentTheme.RowsStyle.BackColor = Color.White;
			dtgda.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgda.CurrentTheme.RowsStyle.ForeColor = Color.Black;
			dtgda.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgda.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
			dataGridViewCellStyle7.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = Color.White;
			dataGridViewCellStyle7.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dataGridViewCellStyle7.ForeColor = Color.Black;
			dataGridViewCellStyle7.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dataGridViewCellStyle7.SelectionForeColor = Color.Black;
			dataGridViewCellStyle7.WrapMode = DataGridViewTriState.False;
			dtgda.DefaultCellStyle = dataGridViewCellStyle7;
			dtgda.EnableHeadersVisualStyles = false;
			dtgda.GridColor = Color.FromArgb(221, 238, 255);
			dtgda.HeaderBackColor = Color.DodgerBlue;
			dtgda.HeaderBgColor = Color.Empty;
			dtgda.HeaderForeColor = Color.White;
			dtgda.Location = new Point(17, 39);
			dtgda.Name = "dtgda";
			dataGridViewCellStyle8.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle8.BackColor = SystemColors.Control;
			dataGridViewCellStyle8.Font = new Font("Segoe UI", 9F);
			dataGridViewCellStyle8.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle8.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle8.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle8.WrapMode = DataGridViewTriState.True;
			dtgda.RowHeadersDefaultCellStyle = dataGridViewCellStyle8;
			dtgda.RowHeadersVisible = false;
			dtgda.RowHeadersWidth = 51;
			dtgda.RowTemplate.Height = 40;
			dtgda.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			dtgda.Size = new Size(698, 144);
			dtgda.TabIndex = 0;
			dtgda.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
			// 
			// tbmada
			// 
			tbmada.AcceptsReturn = false;
			tbmada.AcceptsTab = false;
			tbmada.AnimationSpeed = 200;
			tbmada.AutoCompleteMode = AutoCompleteMode.None;
			tbmada.AutoCompleteSource = AutoCompleteSource.None;
			tbmada.AutoSizeHeight = true;
			tbmada.BackColor = Color.Transparent;
			tbmada.BackgroundImage = (Image)resources.GetObject("tbmada.BackgroundImage");
			tbmada.BorderColorActive = Color.DodgerBlue;
			tbmada.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbmada.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbmada.BorderColorIdle = Color.Silver;
			tbmada.BorderRadius = 1;
			tbmada.BorderThickness = 1;
			tbmada.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbmada.CharacterCasing = CharacterCasing.Normal;
			tbmada.DefaultFont = new Font("Segoe UI", 9.25F);
			tbmada.DefaultText = "";
			tbmada.FillColor = Color.White;
			tbmada.HideSelection = true;
			tbmada.IconLeft = null;
			tbmada.IconLeftCursor = Cursors.IBeam;
			tbmada.IconPadding = 10;
			tbmada.IconRight = null;
			tbmada.IconRightCursor = Cursors.IBeam;
			tbmada.Location = new Point(184, 267);
			tbmada.MaxLength = 32767;
			tbmada.MinimumSize = new Size(1, 1);
			tbmada.Modified = false;
			tbmada.Multiline = false;
			tbmada.Name = "tbmada";
			stateProperties9.BorderColor = Color.DodgerBlue;
			stateProperties9.FillColor = Color.Empty;
			stateProperties9.ForeColor = Color.Empty;
			stateProperties9.PlaceholderForeColor = Color.Empty;
			tbmada.OnActiveState = stateProperties9;
			stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties10.PlaceholderForeColor = Color.DarkGray;
			tbmada.OnDisabledState = stateProperties10;
			stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties11.FillColor = Color.Empty;
			stateProperties11.ForeColor = Color.Empty;
			stateProperties11.PlaceholderForeColor = Color.Empty;
			tbmada.OnHoverState = stateProperties11;
			stateProperties12.BorderColor = Color.Silver;
			stateProperties12.FillColor = Color.White;
			stateProperties12.ForeColor = Color.Empty;
			stateProperties12.PlaceholderForeColor = Color.Empty;
			tbmada.OnIdleState = stateProperties12;
			tbmada.Padding = new Padding(3);
			tbmada.PasswordChar = '\0';
			tbmada.PlaceholderForeColor = Color.Silver;
			tbmada.PlaceholderText = "Enter text";
			tbmada.ReadOnly = false;
			tbmada.ScrollBars = ScrollBars.None;
			tbmada.SelectedText = "";
			tbmada.SelectionLength = 0;
			tbmada.SelectionStart = 0;
			tbmada.ShortcutsEnabled = true;
			tbmada.Size = new Size(135, 35);
			tbmada.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbmada.TabIndex = 1;
			tbmada.TextAlign = HorizontalAlignment.Left;
			tbmada.TextMarginBottom = 0;
			tbmada.TextMarginLeft = 3;
			tbmada.TextMarginTop = 1;
			tbmada.TextPlaceholder = "Enter text";
			tbmada.UseSystemPasswordChar = false;
			tbmada.WordWrap = true;
			// 
			// bunifuLabel1
			// 
			bunifuLabel1.AllowParentOverrides = false;
			bunifuLabel1.AutoEllipsis = false;
			bunifuLabel1.CursorType = Cursors.Default;
			bunifuLabel1.Font = new Font("Segoe UI", 15F);
			bunifuLabel1.Location = new Point(44, 267);
			bunifuLabel1.Name = "bunifuLabel1";
			bunifuLabel1.RightToLeft = RightToLeft.No;
			bunifuLabel1.Size = new Size(110, 35);
			bunifuLabel1.TabIndex = 2;
			bunifuLabel1.Text = "Mã Đề Án";
			bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			bunifuLabel1.Click += bunifuLabel1_Click;
			// 
			// btthem
			// 
			btthem.AllowAnimations = true;
			btthem.AllowMouseEffects = true;
			btthem.AllowToggling = false;
			btthem.AnimationSpeed = 200;
			btthem.AutoGenerateColors = false;
			btthem.AutoRoundBorders = false;
			btthem.AutoSizeLeftIcon = true;
			btthem.AutoSizeRightIcon = true;
			btthem.BackColor = Color.Transparent;
			btthem.BackColor1 = Color.FromArgb(51, 122, 183);
			btthem.BackgroundImage = (Image)resources.GetObject("btthem.BackgroundImage");
			btthem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.ButtonText = "Thêm";
			btthem.ButtonTextMarginLeft = 0;
			btthem.ColorContrastOnClick = 45;
			btthem.ColorContrastOnHover = 45;
			borderEdges6.BottomLeft = true;
			borderEdges6.BottomRight = true;
			borderEdges6.TopLeft = true;
			borderEdges6.TopRight = true;
			btthem.CustomizableEdges = borderEdges6;
			btthem.DialogResult = DialogResult.None;
			btthem.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btthem.DisabledFillColor = Color.Empty;
			btthem.DisabledForecolor = Color.Empty;
			btthem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btthem.Font = new Font("Segoe UI", 9F);
			btthem.ForeColor = Color.White;
			btthem.IconLeft = null;
			btthem.IconLeftAlign = ContentAlignment.MiddleLeft;
			btthem.IconLeftCursor = Cursors.Default;
			btthem.IconLeftPadding = new Padding(11, 3, 3, 3);
			btthem.IconMarginLeft = 11;
			btthem.IconPadding = 10;
			btthem.IconRight = null;
			btthem.IconRightAlign = ContentAlignment.MiddleRight;
			btthem.IconRightCursor = Cursors.Default;
			btthem.IconRightPadding = new Padding(3, 3, 7, 3);
			btthem.IconSize = 25;
			btthem.IdleBorderColor = Color.Empty;
			btthem.IdleBorderRadius = 0;
			btthem.IdleBorderThickness = 0;
			btthem.IdleFillColor = Color.Empty;
			btthem.IdleIconLeftImage = null;
			btthem.IdleIconRightImage = null;
			btthem.IndicateFocus = false;
			btthem.Location = new Point(348, 267);
			btthem.Name = "btthem";
			btthem.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btthem.OnDisabledState.BorderRadius = 1;
			btthem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnDisabledState.BorderThickness = 1;
			btthem.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btthem.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btthem.OnDisabledState.IconLeftImage = null;
			btthem.OnDisabledState.IconRightImage = null;
			btthem.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btthem.onHoverState.BorderRadius = 1;
			btthem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.onHoverState.BorderThickness = 1;
			btthem.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btthem.onHoverState.ForeColor = Color.White;
			btthem.onHoverState.IconLeftImage = null;
			btthem.onHoverState.IconRightImage = null;
			btthem.OnIdleState.BorderColor = Color.DodgerBlue;
			btthem.OnIdleState.BorderRadius = 1;
			btthem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnIdleState.BorderThickness = 1;
			btthem.OnIdleState.FillColor = Color.DodgerBlue;
			btthem.OnIdleState.ForeColor = Color.White;
			btthem.OnIdleState.IconLeftImage = null;
			btthem.OnIdleState.IconRightImage = null;
			btthem.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btthem.OnPressedState.BorderRadius = 1;
			btthem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthem.OnPressedState.BorderThickness = 1;
			btthem.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btthem.OnPressedState.ForeColor = Color.White;
			btthem.OnPressedState.IconLeftImage = null;
			btthem.OnPressedState.IconRightImage = null;
			btthem.Size = new Size(120, 54);
			btthem.TabIndex = 3;
			btthem.TextAlign = ContentAlignment.MiddleCenter;
			btthem.TextAlignment = HorizontalAlignment.Center;
			btthem.TextMarginLeft = 0;
			btthem.TextPadding = new Padding(0);
			btthem.UseDefaultRadiusAndThickness = true;
			btthem.Click += btthem_Click;
			// 
			// btsua
			// 
			btsua.AllowAnimations = true;
			btsua.AllowMouseEffects = true;
			btsua.AllowToggling = false;
			btsua.AnimationSpeed = 200;
			btsua.AutoGenerateColors = false;
			btsua.AutoRoundBorders = false;
			btsua.AutoSizeLeftIcon = true;
			btsua.AutoSizeRightIcon = true;
			btsua.BackColor = Color.Transparent;
			btsua.BackColor1 = Color.FromArgb(51, 122, 183);
			btsua.BackgroundImage = (Image)resources.GetObject("btsua.BackgroundImage");
			btsua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btsua.ButtonText = "Sửa";
			btsua.ButtonTextMarginLeft = 0;
			btsua.ColorContrastOnClick = 45;
			btsua.ColorContrastOnHover = 45;
			borderEdges7.BottomLeft = true;
			borderEdges7.BottomRight = true;
			borderEdges7.TopLeft = true;
			borderEdges7.TopRight = true;
			btsua.CustomizableEdges = borderEdges7;
			btsua.DialogResult = DialogResult.None;
			btsua.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btsua.DisabledFillColor = Color.Empty;
			btsua.DisabledForecolor = Color.Empty;
			btsua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btsua.Font = new Font("Segoe UI", 9F);
			btsua.ForeColor = Color.White;
			btsua.IconLeft = null;
			btsua.IconLeftAlign = ContentAlignment.MiddleLeft;
			btsua.IconLeftCursor = Cursors.Default;
			btsua.IconLeftPadding = new Padding(11, 3, 3, 3);
			btsua.IconMarginLeft = 11;
			btsua.IconPadding = 10;
			btsua.IconRight = null;
			btsua.IconRightAlign = ContentAlignment.MiddleRight;
			btsua.IconRightCursor = Cursors.Default;
			btsua.IconRightPadding = new Padding(3, 3, 7, 3);
			btsua.IconSize = 25;
			btsua.IdleBorderColor = Color.Empty;
			btsua.IdleBorderRadius = 0;
			btsua.IdleBorderThickness = 0;
			btsua.IdleFillColor = Color.Empty;
			btsua.IdleIconLeftImage = null;
			btsua.IdleIconRightImage = null;
			btsua.IndicateFocus = false;
			btsua.Location = new Point(348, 352);
			btsua.Name = "btsua";
			btsua.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btsua.OnDisabledState.BorderRadius = 1;
			btsua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btsua.OnDisabledState.BorderThickness = 1;
			btsua.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btsua.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btsua.OnDisabledState.IconLeftImage = null;
			btsua.OnDisabledState.IconRightImage = null;
			btsua.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btsua.onHoverState.BorderRadius = 1;
			btsua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btsua.onHoverState.BorderThickness = 1;
			btsua.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btsua.onHoverState.ForeColor = Color.White;
			btsua.onHoverState.IconLeftImage = null;
			btsua.onHoverState.IconRightImage = null;
			btsua.OnIdleState.BorderColor = Color.DodgerBlue;
			btsua.OnIdleState.BorderRadius = 1;
			btsua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btsua.OnIdleState.BorderThickness = 1;
			btsua.OnIdleState.FillColor = Color.DodgerBlue;
			btsua.OnIdleState.ForeColor = Color.White;
			btsua.OnIdleState.IconLeftImage = null;
			btsua.OnIdleState.IconRightImage = null;
			btsua.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btsua.OnPressedState.BorderRadius = 1;
			btsua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btsua.OnPressedState.BorderThickness = 1;
			btsua.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btsua.OnPressedState.ForeColor = Color.White;
			btsua.OnPressedState.IconLeftImage = null;
			btsua.OnPressedState.IconRightImage = null;
			btsua.Size = new Size(120, 54);
			btsua.TabIndex = 4;
			btsua.TextAlign = ContentAlignment.MiddleCenter;
			btsua.TextAlignment = HorizontalAlignment.Center;
			btsua.TextMarginLeft = 0;
			btsua.TextPadding = new Padding(0);
			btsua.UseDefaultRadiusAndThickness = true;
			btsua.Click += btsua_Click;
			// 
			// btxoa
			// 
			btxoa.AllowAnimations = true;
			btxoa.AllowMouseEffects = true;
			btxoa.AllowToggling = false;
			btxoa.AnimationSpeed = 200;
			btxoa.AutoGenerateColors = false;
			btxoa.AutoRoundBorders = false;
			btxoa.AutoSizeLeftIcon = true;
			btxoa.AutoSizeRightIcon = true;
			btxoa.BackColor = Color.Transparent;
			btxoa.BackColor1 = Color.FromArgb(51, 122, 183);
			btxoa.BackgroundImage = (Image)resources.GetObject("btxoa.BackgroundImage");
			btxoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btxoa.ButtonText = "Xóa";
			btxoa.ButtonTextMarginLeft = 0;
			btxoa.ColorContrastOnClick = 45;
			btxoa.ColorContrastOnHover = 45;
			borderEdges8.BottomLeft = true;
			borderEdges8.BottomRight = true;
			borderEdges8.TopLeft = true;
			borderEdges8.TopRight = true;
			btxoa.CustomizableEdges = borderEdges8;
			btxoa.DialogResult = DialogResult.None;
			btxoa.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btxoa.DisabledFillColor = Color.Empty;
			btxoa.DisabledForecolor = Color.Empty;
			btxoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btxoa.Font = new Font("Segoe UI", 9F);
			btxoa.ForeColor = Color.White;
			btxoa.IconLeft = null;
			btxoa.IconLeftAlign = ContentAlignment.MiddleLeft;
			btxoa.IconLeftCursor = Cursors.Default;
			btxoa.IconLeftPadding = new Padding(11, 3, 3, 3);
			btxoa.IconMarginLeft = 11;
			btxoa.IconPadding = 10;
			btxoa.IconRight = null;
			btxoa.IconRightAlign = ContentAlignment.MiddleRight;
			btxoa.IconRightCursor = Cursors.Default;
			btxoa.IconRightPadding = new Padding(3, 3, 7, 3);
			btxoa.IconSize = 25;
			btxoa.IdleBorderColor = Color.Empty;
			btxoa.IdleBorderRadius = 0;
			btxoa.IdleBorderThickness = 0;
			btxoa.IdleFillColor = Color.Empty;
			btxoa.IdleIconLeftImage = null;
			btxoa.IdleIconRightImage = null;
			btxoa.IndicateFocus = false;
			btxoa.Location = new Point(495, 267);
			btxoa.Name = "btxoa";
			btxoa.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btxoa.OnDisabledState.BorderRadius = 1;
			btxoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btxoa.OnDisabledState.BorderThickness = 1;
			btxoa.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btxoa.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btxoa.OnDisabledState.IconLeftImage = null;
			btxoa.OnDisabledState.IconRightImage = null;
			btxoa.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btxoa.onHoverState.BorderRadius = 1;
			btxoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btxoa.onHoverState.BorderThickness = 1;
			btxoa.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btxoa.onHoverState.ForeColor = Color.White;
			btxoa.onHoverState.IconLeftImage = null;
			btxoa.onHoverState.IconRightImage = null;
			btxoa.OnIdleState.BorderColor = Color.DodgerBlue;
			btxoa.OnIdleState.BorderRadius = 1;
			btxoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btxoa.OnIdleState.BorderThickness = 1;
			btxoa.OnIdleState.FillColor = Color.DodgerBlue;
			btxoa.OnIdleState.ForeColor = Color.White;
			btxoa.OnIdleState.IconLeftImage = null;
			btxoa.OnIdleState.IconRightImage = null;
			btxoa.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btxoa.OnPressedState.BorderRadius = 1;
			btxoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btxoa.OnPressedState.BorderThickness = 1;
			btxoa.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btxoa.OnPressedState.ForeColor = Color.White;
			btxoa.OnPressedState.IconLeftImage = null;
			btxoa.OnPressedState.IconRightImage = null;
			btxoa.Size = new Size(120, 54);
			btxoa.TabIndex = 5;
			btxoa.TextAlign = ContentAlignment.MiddleCenter;
			btxoa.TextAlignment = HorizontalAlignment.Center;
			btxoa.TextMarginLeft = 0;
			btxoa.TextPadding = new Padding(0);
			btxoa.UseDefaultRadiusAndThickness = true;
			btxoa.Click += btxoa_Click;
			// 
			// btclear
			// 
			btclear.AllowAnimations = true;
			btclear.AllowMouseEffects = true;
			btclear.AllowToggling = false;
			btclear.AnimationSpeed = 200;
			btclear.AutoGenerateColors = false;
			btclear.AutoRoundBorders = false;
			btclear.AutoSizeLeftIcon = true;
			btclear.AutoSizeRightIcon = true;
			btclear.BackColor = Color.Transparent;
			btclear.BackColor1 = Color.FromArgb(51, 122, 183);
			btclear.BackgroundImage = (Image)resources.GetObject("btclear.BackgroundImage");
			btclear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.ButtonText = "Clear";
			btclear.ButtonTextMarginLeft = 0;
			btclear.ColorContrastOnClick = 45;
			btclear.ColorContrastOnHover = 45;
			borderEdges9.BottomLeft = true;
			borderEdges9.BottomRight = true;
			borderEdges9.TopLeft = true;
			borderEdges9.TopRight = true;
			btclear.CustomizableEdges = borderEdges9;
			btclear.DialogResult = DialogResult.None;
			btclear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btclear.DisabledFillColor = Color.Empty;
			btclear.DisabledForecolor = Color.Empty;
			btclear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btclear.Font = new Font("Segoe UI", 9F);
			btclear.ForeColor = Color.White;
			btclear.IconLeft = null;
			btclear.IconLeftAlign = ContentAlignment.MiddleLeft;
			btclear.IconLeftCursor = Cursors.Default;
			btclear.IconLeftPadding = new Padding(11, 3, 3, 3);
			btclear.IconMarginLeft = 11;
			btclear.IconPadding = 10;
			btclear.IconRight = null;
			btclear.IconRightAlign = ContentAlignment.MiddleRight;
			btclear.IconRightCursor = Cursors.Default;
			btclear.IconRightPadding = new Padding(3, 3, 7, 3);
			btclear.IconSize = 25;
			btclear.IdleBorderColor = Color.Empty;
			btclear.IdleBorderRadius = 0;
			btclear.IdleBorderThickness = 0;
			btclear.IdleFillColor = Color.Empty;
			btclear.IdleIconLeftImage = null;
			btclear.IdleIconRightImage = null;
			btclear.IndicateFocus = false;
			btclear.Location = new Point(495, 352);
			btclear.Name = "btclear";
			btclear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btclear.OnDisabledState.BorderRadius = 1;
			btclear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnDisabledState.BorderThickness = 1;
			btclear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btclear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btclear.OnDisabledState.IconLeftImage = null;
			btclear.OnDisabledState.IconRightImage = null;
			btclear.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btclear.onHoverState.BorderRadius = 1;
			btclear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.onHoverState.BorderThickness = 1;
			btclear.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btclear.onHoverState.ForeColor = Color.White;
			btclear.onHoverState.IconLeftImage = null;
			btclear.onHoverState.IconRightImage = null;
			btclear.OnIdleState.BorderColor = Color.DodgerBlue;
			btclear.OnIdleState.BorderRadius = 1;
			btclear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnIdleState.BorderThickness = 1;
			btclear.OnIdleState.FillColor = Color.DodgerBlue;
			btclear.OnIdleState.ForeColor = Color.White;
			btclear.OnIdleState.IconLeftImage = null;
			btclear.OnIdleState.IconRightImage = null;
			btclear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btclear.OnPressedState.BorderRadius = 1;
			btclear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btclear.OnPressedState.BorderThickness = 1;
			btclear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btclear.OnPressedState.ForeColor = Color.White;
			btclear.OnPressedState.IconLeftImage = null;
			btclear.OnPressedState.IconRightImage = null;
			btclear.Size = new Size(120, 54);
			btclear.TabIndex = 6;
			btclear.TextAlign = ContentAlignment.MiddleCenter;
			btclear.TextAlignment = HorizontalAlignment.Center;
			btclear.TextMarginLeft = 0;
			btclear.TextPadding = new Padding(0);
			btclear.UseDefaultRadiusAndThickness = true;
			btclear.Click += btclear_Click;
			// 
			// bunifuButton5
			// 
			bunifuButton5.AllowAnimations = true;
			bunifuButton5.AllowMouseEffects = true;
			bunifuButton5.AllowToggling = false;
			bunifuButton5.AnimationSpeed = 200;
			bunifuButton5.AutoGenerateColors = false;
			bunifuButton5.AutoRoundBorders = false;
			bunifuButton5.AutoSizeLeftIcon = true;
			bunifuButton5.AutoSizeRightIcon = true;
			bunifuButton5.BackColor = Color.Transparent;
			bunifuButton5.BackColor1 = Color.FromArgb(51, 122, 183);
			bunifuButton5.BackgroundImage = (Image)resources.GetObject("bunifuButton5.BackgroundImage");
			bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.ButtonText = "Home";
			bunifuButton5.ButtonTextMarginLeft = 0;
			bunifuButton5.ColorContrastOnClick = 45;
			bunifuButton5.ColorContrastOnHover = 45;
			borderEdges10.BottomLeft = true;
			borderEdges10.BottomRight = true;
			borderEdges10.TopLeft = true;
			borderEdges10.TopRight = true;
			bunifuButton5.CustomizableEdges = borderEdges10;
			bunifuButton5.DialogResult = DialogResult.None;
			bunifuButton5.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.DisabledFillColor = Color.Empty;
			bunifuButton5.DisabledForecolor = Color.Empty;
			bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			bunifuButton5.Font = new Font("Segoe UI", 9F);
			bunifuButton5.ForeColor = Color.White;
			bunifuButton5.IconLeft = null;
			bunifuButton5.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton5.IconLeftCursor = Cursors.Default;
			bunifuButton5.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton5.IconMarginLeft = 11;
			bunifuButton5.IconPadding = 10;
			bunifuButton5.IconRight = null;
			bunifuButton5.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton5.IconRightCursor = Cursors.Default;
			bunifuButton5.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton5.IconSize = 25;
			bunifuButton5.IdleBorderColor = Color.Empty;
			bunifuButton5.IdleBorderRadius = 0;
			bunifuButton5.IdleBorderThickness = 0;
			bunifuButton5.IdleFillColor = Color.Empty;
			bunifuButton5.IdleIconLeftImage = null;
			bunifuButton5.IdleIconRightImage = null;
			bunifuButton5.IndicateFocus = false;
			bunifuButton5.Location = new Point(634, 308);
			bunifuButton5.Name = "bunifuButton5";
			bunifuButton5.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.OnDisabledState.BorderRadius = 1;
			bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnDisabledState.BorderThickness = 1;
			bunifuButton5.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton5.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton5.OnDisabledState.IconLeftImage = null;
			bunifuButton5.OnDisabledState.IconRightImage = null;
			bunifuButton5.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.BorderRadius = 1;
			bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.onHoverState.BorderThickness = 1;
			bunifuButton5.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.ForeColor = Color.White;
			bunifuButton5.onHoverState.IconLeftImage = null;
			bunifuButton5.onHoverState.IconRightImage = null;
			bunifuButton5.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.BorderRadius = 1;
			bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnIdleState.BorderThickness = 1;
			bunifuButton5.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.ForeColor = Color.White;
			bunifuButton5.OnIdleState.IconLeftImage = null;
			bunifuButton5.OnIdleState.IconRightImage = null;
			bunifuButton5.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.BorderRadius = 1;
			bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnPressedState.BorderThickness = 1;
			bunifuButton5.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.ForeColor = Color.White;
			bunifuButton5.OnPressedState.IconLeftImage = null;
			bunifuButton5.OnPressedState.IconRightImage = null;
			bunifuButton5.Size = new Size(120, 54);
			bunifuButton5.TabIndex = 7;
			bunifuButton5.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton5.TextAlignment = HorizontalAlignment.Center;
			bunifuButton5.TextMarginLeft = 0;
			bunifuButton5.TextPadding = new Padding(0);
			bunifuButton5.UseDefaultRadiusAndThickness = true;
			bunifuButton5.Click += bunifuButton5_Click;
			// 
			// bunifuLabel2
			// 
			bunifuLabel2.AllowParentOverrides = false;
			bunifuLabel2.AutoEllipsis = false;
			bunifuLabel2.CursorType = Cursors.Default;
			bunifuLabel2.Font = new Font("Segoe UI", 15F);
			bunifuLabel2.Location = new Point(44, 352);
			bunifuLabel2.Name = "bunifuLabel2";
			bunifuLabel2.RightToLeft = RightToLeft.No;
			bunifuLabel2.Size = new Size(115, 35);
			bunifuLabel2.TabIndex = 9;
			bunifuLabel2.Text = "Tên Đề Án";
			bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbtenda
			// 
			tbtenda.AcceptsReturn = false;
			tbtenda.AcceptsTab = false;
			tbtenda.AnimationSpeed = 200;
			tbtenda.AutoCompleteMode = AutoCompleteMode.None;
			tbtenda.AutoCompleteSource = AutoCompleteSource.None;
			tbtenda.AutoSizeHeight = true;
			tbtenda.BackColor = Color.Transparent;
			tbtenda.BackgroundImage = (Image)resources.GetObject("tbtenda.BackgroundImage");
			tbtenda.BorderColorActive = Color.DodgerBlue;
			tbtenda.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbtenda.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbtenda.BorderColorIdle = Color.Silver;
			tbtenda.BorderRadius = 1;
			tbtenda.BorderThickness = 1;
			tbtenda.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbtenda.CharacterCasing = CharacterCasing.Normal;
			tbtenda.DefaultFont = new Font("Segoe UI", 9.25F);
			tbtenda.DefaultText = "";
			tbtenda.FillColor = Color.White;
			tbtenda.HideSelection = true;
			tbtenda.IconLeft = null;
			tbtenda.IconLeftCursor = Cursors.IBeam;
			tbtenda.IconPadding = 10;
			tbtenda.IconRight = null;
			tbtenda.IconRightCursor = Cursors.IBeam;
			tbtenda.Location = new Point(184, 352);
			tbtenda.MaxLength = 32767;
			tbtenda.MinimumSize = new Size(1, 1);
			tbtenda.Modified = false;
			tbtenda.Multiline = false;
			tbtenda.Name = "tbtenda";
			stateProperties13.BorderColor = Color.DodgerBlue;
			stateProperties13.FillColor = Color.Empty;
			stateProperties13.ForeColor = Color.Empty;
			stateProperties13.PlaceholderForeColor = Color.Empty;
			tbtenda.OnActiveState = stateProperties13;
			stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties14.PlaceholderForeColor = Color.DarkGray;
			tbtenda.OnDisabledState = stateProperties14;
			stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties15.FillColor = Color.Empty;
			stateProperties15.ForeColor = Color.Empty;
			stateProperties15.PlaceholderForeColor = Color.Empty;
			tbtenda.OnHoverState = stateProperties15;
			stateProperties16.BorderColor = Color.Silver;
			stateProperties16.FillColor = Color.White;
			stateProperties16.ForeColor = Color.Empty;
			stateProperties16.PlaceholderForeColor = Color.Empty;
			tbtenda.OnIdleState = stateProperties16;
			tbtenda.Padding = new Padding(3);
			tbtenda.PasswordChar = '\0';
			tbtenda.PlaceholderForeColor = Color.Silver;
			tbtenda.PlaceholderText = "Enter text";
			tbtenda.ReadOnly = false;
			tbtenda.ScrollBars = ScrollBars.None;
			tbtenda.SelectedText = "";
			tbtenda.SelectionLength = 0;
			tbtenda.SelectionStart = 0;
			tbtenda.ShortcutsEnabled = true;
			tbtenda.Size = new Size(135, 35);
			tbtenda.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbtenda.TabIndex = 8;
			tbtenda.TextAlign = HorizontalAlignment.Left;
			tbtenda.TextMarginBottom = 0;
			tbtenda.TextMarginLeft = 3;
			tbtenda.TextMarginTop = 1;
			tbtenda.TextPlaceholder = "Enter text";
			tbtenda.UseSystemPasswordChar = false;
			tbtenda.WordWrap = true;
			// 
			// DeAn
			// 
			AutoScaleDimensions = new SizeF(8F, 20F);
			AutoScaleMode = AutoScaleMode.Font;
			ClientSize = new Size(788, 441);
			Controls.Add(bunifuLabel2);
			Controls.Add(tbtenda);
			Controls.Add(bunifuButton5);
			Controls.Add(btclear);
			Controls.Add(btxoa);
			Controls.Add(btsua);
			Controls.Add(btthem);
			Controls.Add(bunifuLabel1);
			Controls.Add(tbmada);
			Controls.Add(bunifuGroupBox1);
			Name = "DeAn";
			Text = "DeAn";
			Load += DeAn_Load;
			bunifuGroupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)dtgda).EndInit();
			ResumeLayout(false);
			PerformLayout();
		}

		#endregion

		private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
		private Bunifu.UI.WinForms.BunifuDataGridView dtgda;
		private Bunifu.UI.WinForms.BunifuTextBox tbmada;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btthem;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btsua;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btxoa;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btclear;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
		private Bunifu.UI.WinForms.BunifuTextBox tbtenda;
	}
}