namespace QuanLyCongTyDone
{
	partial class NhanVien
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NhanVien));
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
			dtgnv = new Bunifu.UI.WinForms.BunifuDataGridView();
			bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			btsua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			btxoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			btnclear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			tbmanv = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
			bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
			tbtennv = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
			bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
			tbchucvu = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
			tbtienluong = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
			labelmada = new Bunifu.UI.WinForms.BunifuLabel();
			bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
			dtngaysinh = new Bunifu.UI.WinForms.BunifuDatePicker();
			bunifuButton25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			tbmapb = new ComboBox();
			tbmada = new ComboBox();
			tbgioitinh = new ComboBox();
			cbgroupphong = new ComboBox();
			bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
			bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuGroupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)dtgnv).BeginInit();
			SuspendLayout();
			// 
			// bunifuGroupBox1
			// 
			bunifuGroupBox1.BorderColor = Color.LightGray;
			bunifuGroupBox1.BorderRadius = 1;
			bunifuGroupBox1.BorderThickness = 1;
			bunifuGroupBox1.Controls.Add(dtgnv);
			bunifuGroupBox1.Font = new Font("Segoe UI", 9F);
			bunifuGroupBox1.LabelAlign = HorizontalAlignment.Left;
			bunifuGroupBox1.LabelIndent = 10;
			bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
			bunifuGroupBox1.Location = new Point(52, 21);
			bunifuGroupBox1.Name = "bunifuGroupBox1";
			bunifuGroupBox1.Size = new Size(886, 257);
			bunifuGroupBox1.TabIndex = 0;
			bunifuGroupBox1.TabStop = false;
			bunifuGroupBox1.Text = "Nhân Viên";
			// 
			// dtgnv
			// 
			dtgnv.AllowCustomTheming = false;
			dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
			dataGridViewCellStyle1.ForeColor = Color.Black;
			dtgnv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			dtgnv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			dtgnv.BorderStyle = BorderStyle.None;
			dtgnv.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
			dtgnv.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
			dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = Color.White;
			dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dataGridViewCellStyle2.SelectionForeColor = Color.White;
			dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
			dtgnv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			dtgnv.ColumnHeadersHeight = 40;
			dtgnv.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
			dtgnv.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgnv.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
			dtgnv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgnv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
			dtgnv.CurrentTheme.BackColor = Color.White;
			dtgnv.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
			dtgnv.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
			dtgnv.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dtgnv.CurrentTheme.HeaderStyle.ForeColor = Color.White;
			dtgnv.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dtgnv.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
			dtgnv.CurrentTheme.Name = null;
			dtgnv.CurrentTheme.RowsStyle.BackColor = Color.White;
			dtgnv.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgnv.CurrentTheme.RowsStyle.ForeColor = Color.Black;
			dtgnv.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgnv.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = Color.White;
			dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dataGridViewCellStyle3.ForeColor = Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dataGridViewCellStyle3.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
			dtgnv.DefaultCellStyle = dataGridViewCellStyle3;
			dtgnv.EnableHeadersVisualStyles = false;
			dtgnv.GridColor = Color.FromArgb(221, 238, 255);
			dtgnv.HeaderBackColor = Color.DodgerBlue;
			dtgnv.HeaderBgColor = Color.Empty;
			dtgnv.HeaderForeColor = Color.White;
			dtgnv.Location = new Point(25, 32);
			dtgnv.Name = "dtgnv";
			dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = SystemColors.Control;
			dataGridViewCellStyle4.Font = new Font("Segoe UI", 9F);
			dataGridViewCellStyle4.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle4.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle4.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle4.WrapMode = DataGridViewTriState.True;
			dtgnv.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
			dtgnv.RowHeadersVisible = false;
			dtgnv.RowHeadersWidth = 51;
			dtgnv.RowTemplate.Height = 40;
			dtgnv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			dtgnv.Size = new Size(829, 204);
			dtgnv.TabIndex = 0;
			dtgnv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
			dtgnv.CellContentClick += dtgnv_CellContentClick;
			// 
			// bunifuButton21
			// 
			bunifuButton21.AllowAnimations = true;
			bunifuButton21.AllowMouseEffects = true;
			bunifuButton21.AllowToggling = false;
			bunifuButton21.AnimationSpeed = 200;
			bunifuButton21.AutoGenerateColors = false;
			bunifuButton21.AutoRoundBorders = false;
			bunifuButton21.AutoSizeLeftIcon = true;
			bunifuButton21.AutoSizeRightIcon = true;
			bunifuButton21.BackColor = Color.Transparent;
			bunifuButton21.BackColor1 = Color.DodgerBlue;
			bunifuButton21.BackgroundImage = (Image)resources.GetObject("bunifuButton21.BackgroundImage");
			bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton21.ButtonText = "Thêm";
			bunifuButton21.ButtonTextMarginLeft = 0;
			bunifuButton21.ColorContrastOnClick = 45;
			bunifuButton21.ColorContrastOnHover = 45;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			bunifuButton21.CustomizableEdges = borderEdges1;
			bunifuButton21.DialogResult = DialogResult.None;
			bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
			bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
			bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			bunifuButton21.Font = new Font("Segoe UI", 9F);
			bunifuButton21.ForeColor = Color.White;
			bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton21.IconLeftCursor = Cursors.Default;
			bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton21.IconMarginLeft = 11;
			bunifuButton21.IconPadding = 10;
			bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton21.IconRightCursor = Cursors.Default;
			bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton21.IconSize = 25;
			bunifuButton21.IdleBorderColor = Color.DodgerBlue;
			bunifuButton21.IdleBorderRadius = 1;
			bunifuButton21.IdleBorderThickness = 1;
			bunifuButton21.IdleFillColor = Color.DodgerBlue;
			bunifuButton21.IdleIconLeftImage = null;
			bunifuButton21.IdleIconRightImage = null;
			bunifuButton21.IndicateFocus = false;
			bunifuButton21.Location = new Point(141, 494);
			bunifuButton21.Name = "bunifuButton21";
			bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton21.OnDisabledState.BorderRadius = 1;
			bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton21.OnDisabledState.BorderThickness = 1;
			bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton21.OnDisabledState.IconLeftImage = null;
			bunifuButton21.OnDisabledState.IconRightImage = null;
			bunifuButton21.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
			bunifuButton21.onHoverState.BorderRadius = 1;
			bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton21.onHoverState.BorderThickness = 1;
			bunifuButton21.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
			bunifuButton21.onHoverState.ForeColor = Color.White;
			bunifuButton21.onHoverState.IconLeftImage = null;
			bunifuButton21.onHoverState.IconRightImage = null;
			bunifuButton21.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton21.OnIdleState.BorderRadius = 1;
			bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton21.OnIdleState.BorderThickness = 1;
			bunifuButton21.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton21.OnIdleState.ForeColor = Color.White;
			bunifuButton21.OnIdleState.IconLeftImage = null;
			bunifuButton21.OnIdleState.IconRightImage = null;
			bunifuButton21.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton21.OnPressedState.BorderRadius = 1;
			bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton21.OnPressedState.BorderThickness = 1;
			bunifuButton21.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton21.OnPressedState.ForeColor = Color.White;
			bunifuButton21.OnPressedState.IconLeftImage = null;
			bunifuButton21.OnPressedState.IconRightImage = null;
			bunifuButton21.Size = new Size(112, 44);
			bunifuButton21.TabIndex = 1;
			bunifuButton21.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton21.TextAlignment = HorizontalAlignment.Center;
			bunifuButton21.TextMarginLeft = 0;
			bunifuButton21.TextPadding = new Padding(0);
			bunifuButton21.UseDefaultRadiusAndThickness = true;
			bunifuButton21.Click += bunifuButton21_Click;
			// 
			// btsua
			// 
			btsua.AllowAnimations = true;
			btsua.AllowMouseEffects = true;
			btsua.AllowToggling = false;
			btsua.AnimationSpeed = 200;
			btsua.AutoGenerateColors = false;
			btsua.AutoRoundBorders = false;
			btsua.AutoSizeLeftIcon = true;
			btsua.AutoSizeRightIcon = true;
			btsua.BackColor = Color.Transparent;
			btsua.BackColor1 = Color.DodgerBlue;
			btsua.BackgroundImage = (Image)resources.GetObject("btsua.BackgroundImage");
			btsua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btsua.ButtonText = "Sửa";
			btsua.ButtonTextMarginLeft = 0;
			btsua.ColorContrastOnClick = 45;
			btsua.ColorContrastOnHover = 45;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			btsua.CustomizableEdges = borderEdges2;
			btsua.DialogResult = DialogResult.None;
			btsua.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btsua.DisabledFillColor = Color.FromArgb(204, 204, 204);
			btsua.DisabledForecolor = Color.FromArgb(168, 160, 168);
			btsua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			btsua.Font = new Font("Segoe UI", 9F);
			btsua.ForeColor = Color.White;
			btsua.IconLeftAlign = ContentAlignment.MiddleLeft;
			btsua.IconLeftCursor = Cursors.Default;
			btsua.IconLeftPadding = new Padding(11, 3, 3, 3);
			btsua.IconMarginLeft = 11;
			btsua.IconPadding = 10;
			btsua.IconRightAlign = ContentAlignment.MiddleRight;
			btsua.IconRightCursor = Cursors.Default;
			btsua.IconRightPadding = new Padding(3, 3, 7, 3);
			btsua.IconSize = 25;
			btsua.IdleBorderColor = Color.DodgerBlue;
			btsua.IdleBorderRadius = 1;
			btsua.IdleBorderThickness = 1;
			btsua.IdleFillColor = Color.DodgerBlue;
			btsua.IdleIconLeftImage = null;
			btsua.IdleIconRightImage = null;
			btsua.IndicateFocus = false;
			btsua.Location = new Point(283, 494);
			btsua.Name = "btsua";
			btsua.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btsua.OnDisabledState.BorderRadius = 1;
			btsua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btsua.OnDisabledState.BorderThickness = 1;
			btsua.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btsua.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btsua.OnDisabledState.IconLeftImage = null;
			btsua.OnDisabledState.IconRightImage = null;
			btsua.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
			btsua.onHoverState.BorderRadius = 1;
			btsua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btsua.onHoverState.BorderThickness = 1;
			btsua.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
			btsua.onHoverState.ForeColor = Color.White;
			btsua.onHoverState.IconLeftImage = null;
			btsua.onHoverState.IconRightImage = null;
			btsua.OnIdleState.BorderColor = Color.DodgerBlue;
			btsua.OnIdleState.BorderRadius = 1;
			btsua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btsua.OnIdleState.BorderThickness = 1;
			btsua.OnIdleState.FillColor = Color.DodgerBlue;
			btsua.OnIdleState.ForeColor = Color.White;
			btsua.OnIdleState.IconLeftImage = null;
			btsua.OnIdleState.IconRightImage = null;
			btsua.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btsua.OnPressedState.BorderRadius = 1;
			btsua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btsua.OnPressedState.BorderThickness = 1;
			btsua.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btsua.OnPressedState.ForeColor = Color.White;
			btsua.OnPressedState.IconLeftImage = null;
			btsua.OnPressedState.IconRightImage = null;
			btsua.Size = new Size(112, 44);
			btsua.TabIndex = 2;
			btsua.TextAlign = ContentAlignment.MiddleCenter;
			btsua.TextAlignment = HorizontalAlignment.Center;
			btsua.TextMarginLeft = 0;
			btsua.TextPadding = new Padding(0);
			btsua.UseDefaultRadiusAndThickness = true;
			btsua.Click += btsua_Click;
			// 
			// btxoa
			// 
			btxoa.AllowAnimations = true;
			btxoa.AllowMouseEffects = true;
			btxoa.AllowToggling = false;
			btxoa.AnimationSpeed = 200;
			btxoa.AutoGenerateColors = false;
			btxoa.AutoRoundBorders = false;
			btxoa.AutoSizeLeftIcon = true;
			btxoa.AutoSizeRightIcon = true;
			btxoa.BackColor = Color.Transparent;
			btxoa.BackColor1 = Color.DodgerBlue;
			btxoa.BackgroundImage = (Image)resources.GetObject("btxoa.BackgroundImage");
			btxoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btxoa.ButtonText = "Xóa";
			btxoa.ButtonTextMarginLeft = 0;
			btxoa.ColorContrastOnClick = 45;
			btxoa.ColorContrastOnHover = 45;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			btxoa.CustomizableEdges = borderEdges3;
			btxoa.DialogResult = DialogResult.None;
			btxoa.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btxoa.DisabledFillColor = Color.FromArgb(204, 204, 204);
			btxoa.DisabledForecolor = Color.FromArgb(168, 160, 168);
			btxoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			btxoa.Font = new Font("Segoe UI", 9F);
			btxoa.ForeColor = Color.White;
			btxoa.IconLeftAlign = ContentAlignment.MiddleLeft;
			btxoa.IconLeftCursor = Cursors.Default;
			btxoa.IconLeftPadding = new Padding(11, 3, 3, 3);
			btxoa.IconMarginLeft = 11;
			btxoa.IconPadding = 10;
			btxoa.IconRightAlign = ContentAlignment.MiddleRight;
			btxoa.IconRightCursor = Cursors.Default;
			btxoa.IconRightPadding = new Padding(3, 3, 7, 3);
			btxoa.IconSize = 25;
			btxoa.IdleBorderColor = Color.DodgerBlue;
			btxoa.IdleBorderRadius = 1;
			btxoa.IdleBorderThickness = 1;
			btxoa.IdleFillColor = Color.DodgerBlue;
			btxoa.IdleIconLeftImage = null;
			btxoa.IdleIconRightImage = null;
			btxoa.IndicateFocus = false;
			btxoa.Location = new Point(426, 494);
			btxoa.Name = "btxoa";
			btxoa.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btxoa.OnDisabledState.BorderRadius = 1;
			btxoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btxoa.OnDisabledState.BorderThickness = 1;
			btxoa.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btxoa.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btxoa.OnDisabledState.IconLeftImage = null;
			btxoa.OnDisabledState.IconRightImage = null;
			btxoa.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
			btxoa.onHoverState.BorderRadius = 1;
			btxoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btxoa.onHoverState.BorderThickness = 1;
			btxoa.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
			btxoa.onHoverState.ForeColor = Color.White;
			btxoa.onHoverState.IconLeftImage = null;
			btxoa.onHoverState.IconRightImage = null;
			btxoa.OnIdleState.BorderColor = Color.DodgerBlue;
			btxoa.OnIdleState.BorderRadius = 1;
			btxoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btxoa.OnIdleState.BorderThickness = 1;
			btxoa.OnIdleState.FillColor = Color.DodgerBlue;
			btxoa.OnIdleState.ForeColor = Color.White;
			btxoa.OnIdleState.IconLeftImage = null;
			btxoa.OnIdleState.IconRightImage = null;
			btxoa.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btxoa.OnPressedState.BorderRadius = 1;
			btxoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btxoa.OnPressedState.BorderThickness = 1;
			btxoa.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btxoa.OnPressedState.ForeColor = Color.White;
			btxoa.OnPressedState.IconLeftImage = null;
			btxoa.OnPressedState.IconRightImage = null;
			btxoa.Size = new Size(112, 44);
			btxoa.TabIndex = 3;
			btxoa.TextAlign = ContentAlignment.MiddleCenter;
			btxoa.TextAlignment = HorizontalAlignment.Center;
			btxoa.TextMarginLeft = 0;
			btxoa.TextPadding = new Padding(0);
			btxoa.UseDefaultRadiusAndThickness = true;
			btxoa.Click += bunifuButton23_Click_1;
			// 
			// btnclear
			// 
			btnclear.AllowAnimations = true;
			btnclear.AllowMouseEffects = true;
			btnclear.AllowToggling = false;
			btnclear.AnimationSpeed = 200;
			btnclear.AutoGenerateColors = false;
			btnclear.AutoRoundBorders = false;
			btnclear.AutoSizeLeftIcon = true;
			btnclear.AutoSizeRightIcon = true;
			btnclear.BackColor = Color.Transparent;
			btnclear.BackColor1 = Color.DodgerBlue;
			btnclear.BackgroundImage = (Image)resources.GetObject("btnclear.BackgroundImage");
			btnclear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btnclear.ButtonText = "Clear";
			btnclear.ButtonTextMarginLeft = 0;
			btnclear.ColorContrastOnClick = 45;
			btnclear.ColorContrastOnHover = 45;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			btnclear.CustomizableEdges = borderEdges4;
			btnclear.DialogResult = DialogResult.None;
			btnclear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btnclear.DisabledFillColor = Color.FromArgb(204, 204, 204);
			btnclear.DisabledForecolor = Color.FromArgb(168, 160, 168);
			btnclear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			btnclear.Font = new Font("Segoe UI", 9F);
			btnclear.ForeColor = Color.White;
			btnclear.IconLeftAlign = ContentAlignment.MiddleLeft;
			btnclear.IconLeftCursor = Cursors.Default;
			btnclear.IconLeftPadding = new Padding(11, 3, 3, 3);
			btnclear.IconMarginLeft = 11;
			btnclear.IconPadding = 10;
			btnclear.IconRightAlign = ContentAlignment.MiddleRight;
			btnclear.IconRightCursor = Cursors.Default;
			btnclear.IconRightPadding = new Padding(3, 3, 7, 3);
			btnclear.IconSize = 25;
			btnclear.IdleBorderColor = Color.DodgerBlue;
			btnclear.IdleBorderRadius = 1;
			btnclear.IdleBorderThickness = 1;
			btnclear.IdleFillColor = Color.DodgerBlue;
			btnclear.IdleIconLeftImage = null;
			btnclear.IdleIconRightImage = null;
			btnclear.IndicateFocus = false;
			btnclear.Location = new Point(569, 494);
			btnclear.Name = "btnclear";
			btnclear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btnclear.OnDisabledState.BorderRadius = 1;
			btnclear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btnclear.OnDisabledState.BorderThickness = 1;
			btnclear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btnclear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btnclear.OnDisabledState.IconLeftImage = null;
			btnclear.OnDisabledState.IconRightImage = null;
			btnclear.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
			btnclear.onHoverState.BorderRadius = 1;
			btnclear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btnclear.onHoverState.BorderThickness = 1;
			btnclear.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
			btnclear.onHoverState.ForeColor = Color.White;
			btnclear.onHoverState.IconLeftImage = null;
			btnclear.onHoverState.IconRightImage = null;
			btnclear.OnIdleState.BorderColor = Color.DodgerBlue;
			btnclear.OnIdleState.BorderRadius = 1;
			btnclear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btnclear.OnIdleState.BorderThickness = 1;
			btnclear.OnIdleState.FillColor = Color.DodgerBlue;
			btnclear.OnIdleState.ForeColor = Color.White;
			btnclear.OnIdleState.IconLeftImage = null;
			btnclear.OnIdleState.IconRightImage = null;
			btnclear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btnclear.OnPressedState.BorderRadius = 1;
			btnclear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			btnclear.OnPressedState.BorderThickness = 1;
			btnclear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btnclear.OnPressedState.ForeColor = Color.White;
			btnclear.OnPressedState.IconLeftImage = null;
			btnclear.OnPressedState.IconRightImage = null;
			btnclear.Size = new Size(112, 44);
			btnclear.TabIndex = 4;
			btnclear.TextAlign = ContentAlignment.MiddleCenter;
			btnclear.TextAlignment = HorizontalAlignment.Center;
			btnclear.TextMarginLeft = 0;
			btnclear.TextPadding = new Padding(0);
			btnclear.UseDefaultRadiusAndThickness = true;
			btnclear.Click += btnclear_Click;
			// 
			// tbmanv
			// 
			tbmanv.AcceptsReturn = false;
			tbmanv.AcceptsTab = false;
			tbmanv.AnimationSpeed = 200;
			tbmanv.AutoCompleteMode = AutoCompleteMode.None;
			tbmanv.AutoCompleteSource = AutoCompleteSource.None;
			tbmanv.AutoSizeHeight = true;
			tbmanv.BackColor = Color.Transparent;
			tbmanv.BackgroundImage = (Image)resources.GetObject("tbmanv.BackgroundImage");
			tbmanv.BorderColorActive = Color.DodgerBlue;
			tbmanv.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbmanv.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbmanv.BorderColorIdle = Color.Silver;
			tbmanv.BorderRadius = 1;
			tbmanv.BorderThickness = 1;
			tbmanv.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbmanv.CharacterCasing = CharacterCasing.Normal;
			tbmanv.DefaultFont = new Font("Segoe UI", 9.25F);
			tbmanv.DefaultText = "";
			tbmanv.FillColor = Color.White;
			tbmanv.HideSelection = true;
			tbmanv.IconLeft = null;
			tbmanv.IconLeftCursor = Cursors.IBeam;
			tbmanv.IconPadding = 10;
			tbmanv.IconRight = null;
			tbmanv.IconRightCursor = Cursors.IBeam;
			tbmanv.Location = new Point(193, 312);
			tbmanv.MaxLength = 32767;
			tbmanv.MinimumSize = new Size(1, 1);
			tbmanv.Modified = false;
			tbmanv.Multiline = false;
			tbmanv.Name = "tbmanv";
			stateProperties1.BorderColor = Color.DodgerBlue;
			stateProperties1.FillColor = Color.Empty;
			stateProperties1.ForeColor = Color.Empty;
			stateProperties1.PlaceholderForeColor = Color.Empty;
			tbmanv.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties2.PlaceholderForeColor = Color.DarkGray;
			tbmanv.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties3.FillColor = Color.Empty;
			stateProperties3.ForeColor = Color.Empty;
			stateProperties3.PlaceholderForeColor = Color.Empty;
			tbmanv.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = Color.Silver;
			stateProperties4.FillColor = Color.White;
			stateProperties4.ForeColor = Color.Empty;
			stateProperties4.PlaceholderForeColor = Color.Empty;
			tbmanv.OnIdleState = stateProperties4;
			tbmanv.Padding = new Padding(3);
			tbmanv.PasswordChar = '\0';
			tbmanv.PlaceholderForeColor = Color.Silver;
			tbmanv.PlaceholderText = "Enter text";
			tbmanv.ReadOnly = false;
			tbmanv.ScrollBars = ScrollBars.None;
			tbmanv.SelectedText = "";
			tbmanv.SelectionLength = 0;
			tbmanv.SelectionStart = 0;
			tbmanv.ShortcutsEnabled = true;
			tbmanv.Size = new Size(99, 32);
			tbmanv.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbmanv.TabIndex = 6;
			tbmanv.TextAlign = HorizontalAlignment.Left;
			tbmanv.TextMarginBottom = 0;
			tbmanv.TextMarginLeft = 3;
			tbmanv.TextMarginTop = 1;
			tbmanv.TextPlaceholder = "Enter text";
			tbmanv.UseSystemPasswordChar = false;
			tbmanv.WordWrap = true;
			// 
			// bunifuLabel1
			// 
			bunifuLabel1.AllowParentOverrides = false;
			bunifuLabel1.AutoEllipsis = false;
			bunifuLabel1.CursorType = Cursors.Default;
			bunifuLabel1.Font = new Font("Segoe UI", 13F);
			bunifuLabel1.Location = new Point(63, 312);
			bunifuLabel1.Name = "bunifuLabel1";
			bunifuLabel1.RightToLeft = RightToLeft.No;
			bunifuLabel1.Size = new Size(67, 30);
			bunifuLabel1.TabIndex = 7;
			bunifuLabel1.Text = "Mã NV";
			bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// bunifuLabel2
			// 
			bunifuLabel2.AllowParentOverrides = false;
			bunifuLabel2.AutoEllipsis = false;
			bunifuLabel2.CursorType = Cursors.Default;
			bunifuLabel2.Font = new Font("Segoe UI", 13F);
			bunifuLabel2.Location = new Point(63, 369);
			bunifuLabel2.Name = "bunifuLabel2";
			bunifuLabel2.RightToLeft = RightToLeft.No;
			bunifuLabel2.Size = new Size(72, 30);
			bunifuLabel2.TabIndex = 9;
			bunifuLabel2.Text = "Tên NV";
			bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbtennv
			// 
			tbtennv.AcceptsReturn = false;
			tbtennv.AcceptsTab = false;
			tbtennv.AnimationSpeed = 200;
			tbtennv.AutoCompleteMode = AutoCompleteMode.None;
			tbtennv.AutoCompleteSource = AutoCompleteSource.None;
			tbtennv.AutoSizeHeight = true;
			tbtennv.BackColor = Color.Transparent;
			tbtennv.BackgroundImage = (Image)resources.GetObject("tbtennv.BackgroundImage");
			tbtennv.BorderColorActive = Color.DodgerBlue;
			tbtennv.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbtennv.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbtennv.BorderColorIdle = Color.Silver;
			tbtennv.BorderRadius = 1;
			tbtennv.BorderThickness = 1;
			tbtennv.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbtennv.CharacterCasing = CharacterCasing.Normal;
			tbtennv.DefaultFont = new Font("Segoe UI", 9.25F);
			tbtennv.DefaultText = "";
			tbtennv.FillColor = Color.White;
			tbtennv.HideSelection = true;
			tbtennv.IconLeft = null;
			tbtennv.IconLeftCursor = Cursors.IBeam;
			tbtennv.IconPadding = 10;
			tbtennv.IconRight = null;
			tbtennv.IconRightCursor = Cursors.IBeam;
			tbtennv.Location = new Point(193, 369);
			tbtennv.MaxLength = 32767;
			tbtennv.MinimumSize = new Size(1, 1);
			tbtennv.Modified = false;
			tbtennv.Multiline = false;
			tbtennv.Name = "tbtennv";
			stateProperties5.BorderColor = Color.DodgerBlue;
			stateProperties5.FillColor = Color.Empty;
			stateProperties5.ForeColor = Color.Empty;
			stateProperties5.PlaceholderForeColor = Color.Empty;
			tbtennv.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties6.PlaceholderForeColor = Color.DarkGray;
			tbtennv.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties7.FillColor = Color.Empty;
			stateProperties7.ForeColor = Color.Empty;
			stateProperties7.PlaceholderForeColor = Color.Empty;
			tbtennv.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = Color.Silver;
			stateProperties8.FillColor = Color.White;
			stateProperties8.ForeColor = Color.Empty;
			stateProperties8.PlaceholderForeColor = Color.Empty;
			tbtennv.OnIdleState = stateProperties8;
			tbtennv.Padding = new Padding(3);
			tbtennv.PasswordChar = '\0';
			tbtennv.PlaceholderForeColor = Color.Silver;
			tbtennv.PlaceholderText = "Enter text";
			tbtennv.ReadOnly = false;
			tbtennv.ScrollBars = ScrollBars.None;
			tbtennv.SelectedText = "";
			tbtennv.SelectionLength = 0;
			tbtennv.SelectionStart = 0;
			tbtennv.ShortcutsEnabled = true;
			tbtennv.Size = new Size(99, 32);
			tbtennv.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbtennv.TabIndex = 8;
			tbtennv.TextAlign = HorizontalAlignment.Left;
			tbtennv.TextMarginBottom = 0;
			tbtennv.TextMarginLeft = 3;
			tbtennv.TextMarginTop = 1;
			tbtennv.TextPlaceholder = "Enter text";
			tbtennv.UseSystemPasswordChar = false;
			tbtennv.WordWrap = true;
			// 
			// bunifuLabel3
			// 
			bunifuLabel3.AllowParentOverrides = false;
			bunifuLabel3.AutoEllipsis = false;
			bunifuLabel3.CursorType = Cursors.Default;
			bunifuLabel3.Font = new Font("Segoe UI", 13F);
			bunifuLabel3.Location = new Point(345, 312);
			bunifuLabel3.Name = "bunifuLabel3";
			bunifuLabel3.RightToLeft = RightToLeft.No;
			bunifuLabel3.Size = new Size(85, 30);
			bunifuLabel3.TabIndex = 11;
			bunifuLabel3.Text = "Giới Tính";
			bunifuLabel3.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// bunifuLabel4
			// 
			bunifuLabel4.AllowParentOverrides = false;
			bunifuLabel4.AutoEllipsis = false;
			bunifuLabel4.CursorType = Cursors.Default;
			bunifuLabel4.Font = new Font("Segoe UI", 13F);
			bunifuLabel4.Location = new Point(345, 369);
			bunifuLabel4.Name = "bunifuLabel4";
			bunifuLabel4.RightToLeft = RightToLeft.No;
			bunifuLabel4.Size = new Size(81, 30);
			bunifuLabel4.TabIndex = 13;
			bunifuLabel4.Text = "Chức Vụ ";
			bunifuLabel4.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbchucvu
			// 
			tbchucvu.AcceptsReturn = false;
			tbchucvu.AcceptsTab = false;
			tbchucvu.AnimationSpeed = 200;
			tbchucvu.AutoCompleteMode = AutoCompleteMode.None;
			tbchucvu.AutoCompleteSource = AutoCompleteSource.None;
			tbchucvu.AutoSizeHeight = true;
			tbchucvu.BackColor = Color.Transparent;
			tbchucvu.BackgroundImage = (Image)resources.GetObject("tbchucvu.BackgroundImage");
			tbchucvu.BorderColorActive = Color.DodgerBlue;
			tbchucvu.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbchucvu.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbchucvu.BorderColorIdle = Color.Silver;
			tbchucvu.BorderRadius = 1;
			tbchucvu.BorderThickness = 1;
			tbchucvu.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbchucvu.CharacterCasing = CharacterCasing.Normal;
			tbchucvu.DefaultFont = new Font("Segoe UI", 9.25F);
			tbchucvu.DefaultText = "";
			tbchucvu.FillColor = Color.White;
			tbchucvu.HideSelection = true;
			tbchucvu.IconLeft = null;
			tbchucvu.IconLeftCursor = Cursors.IBeam;
			tbchucvu.IconPadding = 10;
			tbchucvu.IconRight = null;
			tbchucvu.IconRightCursor = Cursors.IBeam;
			tbchucvu.Location = new Point(475, 369);
			tbchucvu.MaxLength = 32767;
			tbchucvu.MinimumSize = new Size(1, 1);
			tbchucvu.Modified = false;
			tbchucvu.Multiline = false;
			tbchucvu.Name = "tbchucvu";
			stateProperties9.BorderColor = Color.DodgerBlue;
			stateProperties9.FillColor = Color.Empty;
			stateProperties9.ForeColor = Color.Empty;
			stateProperties9.PlaceholderForeColor = Color.Empty;
			tbchucvu.OnActiveState = stateProperties9;
			stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties10.PlaceholderForeColor = Color.DarkGray;
			tbchucvu.OnDisabledState = stateProperties10;
			stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties11.FillColor = Color.Empty;
			stateProperties11.ForeColor = Color.Empty;
			stateProperties11.PlaceholderForeColor = Color.Empty;
			tbchucvu.OnHoverState = stateProperties11;
			stateProperties12.BorderColor = Color.Silver;
			stateProperties12.FillColor = Color.White;
			stateProperties12.ForeColor = Color.Empty;
			stateProperties12.PlaceholderForeColor = Color.Empty;
			tbchucvu.OnIdleState = stateProperties12;
			tbchucvu.Padding = new Padding(3);
			tbchucvu.PasswordChar = '\0';
			tbchucvu.PlaceholderForeColor = Color.Silver;
			tbchucvu.PlaceholderText = "Enter text";
			tbchucvu.ReadOnly = false;
			tbchucvu.ScrollBars = ScrollBars.None;
			tbchucvu.SelectedText = "";
			tbchucvu.SelectionLength = 0;
			tbchucvu.SelectionStart = 0;
			tbchucvu.ShortcutsEnabled = true;
			tbchucvu.Size = new Size(99, 32);
			tbchucvu.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbchucvu.TabIndex = 12;
			tbchucvu.TextAlign = HorizontalAlignment.Left;
			tbchucvu.TextMarginBottom = 0;
			tbchucvu.TextMarginLeft = 3;
			tbchucvu.TextMarginTop = 1;
			tbchucvu.TextPlaceholder = "Enter text";
			tbchucvu.UseSystemPasswordChar = false;
			tbchucvu.WordWrap = true;
			// 
			// bunifuLabel5
			// 
			bunifuLabel5.AllowParentOverrides = false;
			bunifuLabel5.AutoEllipsis = false;
			bunifuLabel5.CursorType = Cursors.Default;
			bunifuLabel5.Font = new Font("Segoe UI", 13F);
			bunifuLabel5.Location = new Point(345, 432);
			bunifuLabel5.Name = "bunifuLabel5";
			bunifuLabel5.RightToLeft = RightToLeft.No;
			bunifuLabel5.Size = new Size(108, 30);
			bunifuLabel5.TabIndex = 15;
			bunifuLabel5.Text = "Tiền Lương";
			bunifuLabel5.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbtienluong
			// 
			tbtienluong.AcceptsReturn = false;
			tbtienluong.AcceptsTab = false;
			tbtienluong.AnimationSpeed = 200;
			tbtienluong.AutoCompleteMode = AutoCompleteMode.None;
			tbtienluong.AutoCompleteSource = AutoCompleteSource.None;
			tbtienluong.AutoSizeHeight = true;
			tbtienluong.BackColor = Color.Transparent;
			tbtienluong.BackgroundImage = (Image)resources.GetObject("tbtienluong.BackgroundImage");
			tbtienluong.BorderColorActive = Color.DodgerBlue;
			tbtienluong.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbtienluong.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbtienluong.BorderColorIdle = Color.Silver;
			tbtienluong.BorderRadius = 1;
			tbtienluong.BorderThickness = 1;
			tbtienluong.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbtienluong.CharacterCasing = CharacterCasing.Normal;
			tbtienluong.DefaultFont = new Font("Segoe UI", 9.25F);
			tbtienluong.DefaultText = "";
			tbtienluong.FillColor = Color.White;
			tbtienluong.HideSelection = true;
			tbtienluong.IconLeft = null;
			tbtienluong.IconLeftCursor = Cursors.IBeam;
			tbtienluong.IconPadding = 10;
			tbtienluong.IconRight = null;
			tbtienluong.IconRightCursor = Cursors.IBeam;
			tbtienluong.Location = new Point(475, 430);
			tbtienluong.MaxLength = 32767;
			tbtienluong.MinimumSize = new Size(1, 1);
			tbtienluong.Modified = false;
			tbtienluong.Multiline = false;
			tbtienluong.Name = "tbtienluong";
			stateProperties13.BorderColor = Color.DodgerBlue;
			stateProperties13.FillColor = Color.Empty;
			stateProperties13.ForeColor = Color.Empty;
			stateProperties13.PlaceholderForeColor = Color.Empty;
			tbtienluong.OnActiveState = stateProperties13;
			stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties14.PlaceholderForeColor = Color.DarkGray;
			tbtienluong.OnDisabledState = stateProperties14;
			stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties15.FillColor = Color.Empty;
			stateProperties15.ForeColor = Color.Empty;
			stateProperties15.PlaceholderForeColor = Color.Empty;
			tbtienluong.OnHoverState = stateProperties15;
			stateProperties16.BorderColor = Color.Silver;
			stateProperties16.FillColor = Color.White;
			stateProperties16.ForeColor = Color.Empty;
			stateProperties16.PlaceholderForeColor = Color.Empty;
			tbtienluong.OnIdleState = stateProperties16;
			tbtienluong.Padding = new Padding(3);
			tbtienluong.PasswordChar = '\0';
			tbtienluong.PlaceholderForeColor = Color.Silver;
			tbtienluong.PlaceholderText = "Enter text";
			tbtienluong.ReadOnly = false;
			tbtienluong.ScrollBars = ScrollBars.None;
			tbtienluong.SelectedText = "";
			tbtienluong.SelectionLength = 0;
			tbtienluong.SelectionStart = 0;
			tbtienluong.ShortcutsEnabled = true;
			tbtienluong.Size = new Size(99, 32);
			tbtienluong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbtienluong.TabIndex = 14;
			tbtienluong.TextAlign = HorizontalAlignment.Left;
			tbtienluong.TextMarginBottom = 0;
			tbtienluong.TextMarginLeft = 3;
			tbtienluong.TextMarginTop = 1;
			tbtienluong.TextPlaceholder = "Enter text";
			tbtienluong.UseSystemPasswordChar = false;
			tbtienluong.WordWrap = true;
			// 
			// bunifuLabel6
			// 
			bunifuLabel6.AllowParentOverrides = false;
			bunifuLabel6.AutoEllipsis = false;
			bunifuLabel6.CursorType = Cursors.Default;
			bunifuLabel6.Font = new Font("Segoe UI", 13F);
			bunifuLabel6.Location = new Point(625, 312);
			bunifuLabel6.Name = "bunifuLabel6";
			bunifuLabel6.RightToLeft = RightToLeft.No;
			bunifuLabel6.Size = new Size(147, 30);
			bunifuLabel6.TabIndex = 17;
			bunifuLabel6.Text = "Phòng Hiện Tại";
			bunifuLabel6.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// labelmada
			// 
			labelmada.AllowParentOverrides = false;
			labelmada.AutoEllipsis = false;
			labelmada.CursorType = Cursors.Default;
			labelmada.Font = new Font("Segoe UI", 13F);
			labelmada.Location = new Point(625, 369);
			labelmada.Name = "labelmada";
			labelmada.RightToLeft = RightToLeft.No;
			labelmada.Size = new Size(59, 30);
			labelmada.TabIndex = 19;
			labelmada.Text = "Đề Án";
			labelmada.TextAlignment = ContentAlignment.TopLeft;
			labelmada.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// bunifuLabel8
			// 
			bunifuLabel8.AllowParentOverrides = false;
			bunifuLabel8.AutoEllipsis = false;
			bunifuLabel8.CursorType = Cursors.Default;
			bunifuLabel8.Font = new Font("Segoe UI", 13F);
			bunifuLabel8.Location = new Point(63, 432);
			bunifuLabel8.Name = "bunifuLabel8";
			bunifuLabel8.RightToLeft = RightToLeft.No;
			bunifuLabel8.Size = new Size(98, 30);
			bunifuLabel8.TabIndex = 20;
			bunifuLabel8.Text = "Ngày Sinh";
			bunifuLabel8.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// dtngaysinh
			// 
			dtngaysinh.BackColor = Color.Transparent;
			dtngaysinh.BorderColor = Color.Silver;
			dtngaysinh.BorderRadius = 1;
			dtngaysinh.Color = Color.Silver;
			dtngaysinh.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
			dtngaysinh.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
			dtngaysinh.DisabledColor = Color.Gray;
			dtngaysinh.DisplayWeekNumbers = false;
			dtngaysinh.DPHeight = 0;
			dtngaysinh.DropDownAlign = LeftRightAlignment.Right;
			dtngaysinh.FillDatePicker = false;
			dtngaysinh.Font = new Font("Segoe UI", 9F);
			dtngaysinh.ForeColor = Color.Black;
			dtngaysinh.Format = DateTimePickerFormat.Short;
			dtngaysinh.Icon = (Image)resources.GetObject("dtngaysinh.Icon");
			dtngaysinh.IconColor = Color.Gray;
			dtngaysinh.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
			dtngaysinh.LeftTextMargin = 5;
			dtngaysinh.Location = new Point(193, 432);
			dtngaysinh.MinimumSize = new Size(0, 32);
			dtngaysinh.Name = "dtngaysinh";
			dtngaysinh.Size = new Size(126, 32);
			dtngaysinh.TabIndex = 21;
			// 
			// bunifuButton25
			// 
			bunifuButton25.AllowAnimations = true;
			bunifuButton25.AllowMouseEffects = true;
			bunifuButton25.AllowToggling = false;
			bunifuButton25.AnimationSpeed = 200;
			bunifuButton25.AutoGenerateColors = false;
			bunifuButton25.AutoRoundBorders = false;
			bunifuButton25.AutoSizeLeftIcon = true;
			bunifuButton25.AutoSizeRightIcon = true;
			bunifuButton25.BackColor = Color.Transparent;
			bunifuButton25.BackColor1 = Color.DodgerBlue;
			bunifuButton25.BackgroundImage = (Image)resources.GetObject("bunifuButton25.BackgroundImage");
			bunifuButton25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton25.ButtonText = "Home";
			bunifuButton25.ButtonTextMarginLeft = 0;
			bunifuButton25.ColorContrastOnClick = 45;
			bunifuButton25.ColorContrastOnHover = 45;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			bunifuButton25.CustomizableEdges = borderEdges5;
			bunifuButton25.DialogResult = DialogResult.None;
			bunifuButton25.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton25.DisabledFillColor = Color.FromArgb(204, 204, 204);
			bunifuButton25.DisabledForecolor = Color.FromArgb(168, 160, 168);
			bunifuButton25.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			bunifuButton25.Font = new Font("Segoe UI", 9F);
			bunifuButton25.ForeColor = Color.White;
			bunifuButton25.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton25.IconLeftCursor = Cursors.Default;
			bunifuButton25.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton25.IconMarginLeft = 11;
			bunifuButton25.IconPadding = 10;
			bunifuButton25.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton25.IconRightCursor = Cursors.Default;
			bunifuButton25.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton25.IconSize = 25;
			bunifuButton25.IdleBorderColor = Color.DodgerBlue;
			bunifuButton25.IdleBorderRadius = 1;
			bunifuButton25.IdleBorderThickness = 1;
			bunifuButton25.IdleFillColor = Color.DodgerBlue;
			bunifuButton25.IdleIconLeftImage = null;
			bunifuButton25.IdleIconRightImage = null;
			bunifuButton25.IndicateFocus = false;
			bunifuButton25.Location = new Point(713, 494);
			bunifuButton25.Name = "bunifuButton25";
			bunifuButton25.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton25.OnDisabledState.BorderRadius = 1;
			bunifuButton25.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton25.OnDisabledState.BorderThickness = 1;
			bunifuButton25.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton25.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton25.OnDisabledState.IconLeftImage = null;
			bunifuButton25.OnDisabledState.IconRightImage = null;
			bunifuButton25.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
			bunifuButton25.onHoverState.BorderRadius = 1;
			bunifuButton25.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton25.onHoverState.BorderThickness = 1;
			bunifuButton25.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
			bunifuButton25.onHoverState.ForeColor = Color.White;
			bunifuButton25.onHoverState.IconLeftImage = null;
			bunifuButton25.onHoverState.IconRightImage = null;
			bunifuButton25.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton25.OnIdleState.BorderRadius = 1;
			bunifuButton25.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton25.OnIdleState.BorderThickness = 1;
			bunifuButton25.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton25.OnIdleState.ForeColor = Color.White;
			bunifuButton25.OnIdleState.IconLeftImage = null;
			bunifuButton25.OnIdleState.IconRightImage = null;
			bunifuButton25.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton25.OnPressedState.BorderRadius = 1;
			bunifuButton25.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			bunifuButton25.OnPressedState.BorderThickness = 1;
			bunifuButton25.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton25.OnPressedState.ForeColor = Color.White;
			bunifuButton25.OnPressedState.IconLeftImage = null;
			bunifuButton25.OnPressedState.IconRightImage = null;
			bunifuButton25.Size = new Size(112, 44);
			bunifuButton25.TabIndex = 22;
			bunifuButton25.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton25.TextAlignment = HorizontalAlignment.Center;
			bunifuButton25.TextMarginLeft = 0;
			bunifuButton25.TextPadding = new Padding(0);
			bunifuButton25.UseDefaultRadiusAndThickness = true;
			bunifuButton25.Click += bunifuButton25_Click;
			// 
			// tbmapb
			// 
			tbmapb.FormattingEnabled = true;
			tbmapb.Location = new Point(755, 316);
			tbmapb.Name = "tbmapb";
			tbmapb.Size = new Size(109, 28);
			tbmapb.TabIndex = 23;
			tbmapb.KeyPress += tbmapb_KeyPress;
			// 
			// tbmada
			// 
			tbmada.FormattingEnabled = true;
			tbmada.Location = new Point(755, 369);
			tbmada.Name = "tbmada";
			tbmada.Size = new Size(109, 28);
			tbmada.TabIndex = 24;
			tbmada.KeyPress += tbmada_KeyPress;
			// 
			// tbgioitinh
			// 
			tbgioitinh.FormattingEnabled = true;
			tbgioitinh.Items.AddRange(new object[] { "Nam", "Nu" });
			tbgioitinh.Location = new Point(475, 316);
			tbgioitinh.Name = "tbgioitinh";
			tbgioitinh.Size = new Size(99, 28);
			tbgioitinh.TabIndex = 25;
			tbgioitinh.KeyPress += tbgioitinh_KeyPress;
			// 
			// cbgroupphong
			// 
			cbgroupphong.FormattingEnabled = true;
			cbgroupphong.Location = new Point(755, 430);
			cbgroupphong.Name = "cbgroupphong";
			cbgroupphong.Size = new Size(109, 28);
			cbgroupphong.TabIndex = 26;
			cbgroupphong.SelectedIndexChanged += cbgroupphong_SelectedIndexChanged;
			// 
			// bunifuLabel7
			// 
			bunifuLabel7.AllowParentOverrides = false;
			bunifuLabel7.AutoEllipsis = false;
			bunifuLabel7.CursorType = Cursors.Default;
			bunifuLabel7.Font = new Font("Segoe UI", 13F);
			bunifuLabel7.Location = new Point(625, 430);
			bunifuLabel7.Name = "bunifuLabel7";
			bunifuLabel7.RightToLeft = RightToLeft.No;
			bunifuLabel7.Size = new Size(119, 30);
			bunifuLabel7.TabIndex = 27;
			bunifuLabel7.Text = "Chọn Phòng";
			bunifuLabel7.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// bunifuButton1
			// 
			bunifuButton1.AllowAnimations = true;
			bunifuButton1.AllowMouseEffects = true;
			bunifuButton1.AllowToggling = false;
			bunifuButton1.AnimationSpeed = 200;
			bunifuButton1.AutoGenerateColors = false;
			bunifuButton1.AutoRoundBorders = false;
			bunifuButton1.AutoSizeLeftIcon = true;
			bunifuButton1.AutoSizeRightIcon = true;
			bunifuButton1.BackColor = Color.Transparent;
			bunifuButton1.BackColor1 = Color.FromArgb(51, 122, 183);
			bunifuButton1.BackgroundImage = (Image)resources.GetObject("bunifuButton1.BackgroundImage");
			bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton1.ButtonText = "Đăng Xuất";
			bunifuButton1.ButtonTextMarginLeft = 0;
			bunifuButton1.ColorContrastOnClick = 45;
			bunifuButton1.ColorContrastOnHover = 45;
			borderEdges6.BottomLeft = true;
			borderEdges6.BottomRight = true;
			borderEdges6.TopLeft = true;
			borderEdges6.TopRight = true;
			bunifuButton1.CustomizableEdges = borderEdges6;
			bunifuButton1.DialogResult = DialogResult.None;
			bunifuButton1.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton1.DisabledFillColor = Color.Empty;
			bunifuButton1.DisabledForecolor = Color.Empty;
			bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			bunifuButton1.Font = new Font("Segoe UI", 9F);
			bunifuButton1.ForeColor = Color.White;
			bunifuButton1.IconLeft = null;
			bunifuButton1.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton1.IconLeftCursor = Cursors.Default;
			bunifuButton1.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton1.IconMarginLeft = 11;
			bunifuButton1.IconPadding = 10;
			bunifuButton1.IconRight = null;
			bunifuButton1.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton1.IconRightCursor = Cursors.Default;
			bunifuButton1.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton1.IconSize = 25;
			bunifuButton1.IdleBorderColor = Color.Empty;
			bunifuButton1.IdleBorderRadius = 0;
			bunifuButton1.IdleBorderThickness = 0;
			bunifuButton1.IdleFillColor = Color.Empty;
			bunifuButton1.IdleIconLeftImage = null;
			bunifuButton1.IdleIconRightImage = null;
			bunifuButton1.IndicateFocus = false;
			bunifuButton1.Location = new Point(713, 494);
			bunifuButton1.Name = "bunifuButton1";
			bunifuButton1.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton1.OnDisabledState.BorderRadius = 1;
			bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton1.OnDisabledState.BorderThickness = 1;
			bunifuButton1.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton1.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton1.OnDisabledState.IconLeftImage = null;
			bunifuButton1.OnDisabledState.IconRightImage = null;
			bunifuButton1.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			bunifuButton1.onHoverState.BorderRadius = 1;
			bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton1.onHoverState.BorderThickness = 1;
			bunifuButton1.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			bunifuButton1.onHoverState.ForeColor = Color.White;
			bunifuButton1.onHoverState.IconLeftImage = null;
			bunifuButton1.onHoverState.IconRightImage = null;
			bunifuButton1.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton1.OnIdleState.BorderRadius = 1;
			bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton1.OnIdleState.BorderThickness = 1;
			bunifuButton1.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton1.OnIdleState.ForeColor = Color.White;
			bunifuButton1.OnIdleState.IconLeftImage = null;
			bunifuButton1.OnIdleState.IconRightImage = null;
			bunifuButton1.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton1.OnPressedState.BorderRadius = 1;
			bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton1.OnPressedState.BorderThickness = 1;
			bunifuButton1.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton1.OnPressedState.ForeColor = Color.White;
			bunifuButton1.OnPressedState.IconLeftImage = null;
			bunifuButton1.OnPressedState.IconRightImage = null;
			bunifuButton1.Size = new Size(112, 44);
			bunifuButton1.TabIndex = 28;
			bunifuButton1.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton1.TextAlignment = HorizontalAlignment.Center;
			bunifuButton1.TextMarginLeft = 0;
			bunifuButton1.TextPadding = new Padding(0);
			bunifuButton1.UseDefaultRadiusAndThickness = true;
			bunifuButton1.Click += bunifuButton1_Click;
			// 
			// NhanVien
			// 
			AutoScaleDimensions = new SizeF(8F, 20F);
			AutoScaleMode = AutoScaleMode.Font;
			ClientSize = new Size(963, 574);
			Controls.Add(bunifuButton1);
			Controls.Add(bunifuLabel7);
			Controls.Add(cbgroupphong);
			Controls.Add(tbgioitinh);
			Controls.Add(tbmada);
			Controls.Add(tbmapb);
			Controls.Add(bunifuButton25);
			Controls.Add(dtngaysinh);
			Controls.Add(bunifuLabel8);
			Controls.Add(labelmada);
			Controls.Add(bunifuLabel6);
			Controls.Add(bunifuLabel5);
			Controls.Add(tbtienluong);
			Controls.Add(bunifuLabel4);
			Controls.Add(tbchucvu);
			Controls.Add(bunifuLabel3);
			Controls.Add(bunifuLabel2);
			Controls.Add(tbtennv);
			Controls.Add(bunifuLabel1);
			Controls.Add(tbmanv);
			Controls.Add(btnclear);
			Controls.Add(btxoa);
			Controls.Add(btsua);
			Controls.Add(bunifuButton21);
			Controls.Add(bunifuGroupBox1);
			Name = "NhanVien";
			Text = "NhanVien";
			Load += NhanVien_Load;
			bunifuGroupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)dtgnv).EndInit();
			ResumeLayout(false);
			PerformLayout();
		}

		#endregion

		private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
		private Bunifu.UI.WinForms.BunifuDataGridView dtgnv;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btsua;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btxoa;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnclear;
		private Bunifu.UI.WinForms.BunifuTextBox tbmanv;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
		private Bunifu.UI.WinForms.BunifuTextBox tbtennv;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
		private Bunifu.UI.WinForms.BunifuTextBox tbchucvu;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
		private Bunifu.UI.WinForms.BunifuTextBox tbtienluong;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
		private Bunifu.UI.WinForms.BunifuLabel labelmada;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
		private Bunifu.UI.WinForms.BunifuDatePicker dtngaysinh;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton25;
		private ComboBox tbmapb;
		private ComboBox tbmada;
		private ComboBox tbgioitinh;
		private ComboBox cbgroupphong;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
	}
}