namespace QuanLyCongTyDone
{
	partial class PhongBan
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
			DataGridViewCellStyle dataGridViewCellStyle4 = new DataGridViewCellStyle();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PhongBan));
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
			dtgpb = new Bunifu.UI.WinForms.BunifuDataGridView();
			tbmapb1 = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
			btthempb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btnsuapb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btnxoapb = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			btnclear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
			tbtenpb2 = new Bunifu.UI.WinForms.BunifuTextBox();
			bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
			bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
			tbtentp3 = new ComboBox();
			tbmada4 = new ComboBox();
			bunifuGroupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)dtgpb).BeginInit();
			SuspendLayout();
			// 
			// bunifuGroupBox1
			// 
			bunifuGroupBox1.BorderColor = Color.LightGray;
			bunifuGroupBox1.BorderRadius = 1;
			bunifuGroupBox1.BorderThickness = 1;
			bunifuGroupBox1.Controls.Add(dtgpb);
			bunifuGroupBox1.Font = new Font("Segoe UI", 9F);
			bunifuGroupBox1.LabelAlign = HorizontalAlignment.Left;
			bunifuGroupBox1.LabelIndent = 10;
			bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
			bunifuGroupBox1.Location = new Point(57, 18);
			bunifuGroupBox1.Name = "bunifuGroupBox1";
			bunifuGroupBox1.Size = new Size(700, 236);
			bunifuGroupBox1.TabIndex = 0;
			bunifuGroupBox1.TabStop = false;
			bunifuGroupBox1.Text = "Phòng Ban";
			// 
			// dtgpb
			// 
			dtgpb.AllowCustomTheming = false;
			dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
			dataGridViewCellStyle1.ForeColor = Color.Black;
			dtgpb.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
			dtgpb.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
			dtgpb.BorderStyle = BorderStyle.None;
			dtgpb.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
			dtgpb.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
			dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dataGridViewCellStyle2.ForeColor = Color.White;
			dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dataGridViewCellStyle2.SelectionForeColor = Color.White;
			dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
			dtgpb.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			dtgpb.ColumnHeadersHeight = 40;
			dtgpb.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
			dtgpb.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgpb.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
			dtgpb.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgpb.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
			dtgpb.CurrentTheme.BackColor = Color.White;
			dtgpb.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
			dtgpb.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
			dtgpb.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
			dtgpb.CurrentTheme.HeaderStyle.ForeColor = Color.White;
			dtgpb.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
			dtgpb.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
			dtgpb.CurrentTheme.Name = null;
			dtgpb.CurrentTheme.RowsStyle.BackColor = Color.White;
			dtgpb.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dtgpb.CurrentTheme.RowsStyle.ForeColor = Color.Black;
			dtgpb.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dtgpb.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = Color.White;
			dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
			dataGridViewCellStyle3.ForeColor = Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
			dataGridViewCellStyle3.SelectionForeColor = Color.Black;
			dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
			dtgpb.DefaultCellStyle = dataGridViewCellStyle3;
			dtgpb.EnableHeadersVisualStyles = false;
			dtgpb.GridColor = Color.FromArgb(221, 238, 255);
			dtgpb.HeaderBackColor = Color.DodgerBlue;
			dtgpb.HeaderBgColor = Color.Empty;
			dtgpb.HeaderForeColor = Color.White;
			dtgpb.Location = new Point(15, 40);
			dtgpb.Name = "dtgpb";
			dataGridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = SystemColors.Control;
			dataGridViewCellStyle4.Font = new Font("Segoe UI", 9F);
			dataGridViewCellStyle4.ForeColor = SystemColors.WindowText;
			dataGridViewCellStyle4.SelectionBackColor = SystemColors.Highlight;
			dataGridViewCellStyle4.SelectionForeColor = SystemColors.HighlightText;
			dataGridViewCellStyle4.WrapMode = DataGridViewTriState.True;
			dtgpb.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
			dtgpb.RowHeadersVisible = false;
			dtgpb.RowHeadersWidth = 51;
			dtgpb.RowTemplate.Height = 40;
			dtgpb.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
			dtgpb.Size = new Size(670, 179);
			dtgpb.TabIndex = 0;
			dtgpb.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
			dtgpb.CellContentClick += dtgpb_CellContentClick;
			// 
			// tbmapb1
			// 
			tbmapb1.AcceptsReturn = false;
			tbmapb1.AcceptsTab = false;
			tbmapb1.AnimationSpeed = 200;
			tbmapb1.AutoCompleteMode = AutoCompleteMode.None;
			tbmapb1.AutoCompleteSource = AutoCompleteSource.None;
			tbmapb1.AutoSizeHeight = true;
			tbmapb1.BackColor = Color.Transparent;
			tbmapb1.BackgroundImage = (Image)resources.GetObject("tbmapb1.BackgroundImage");
			tbmapb1.BorderColorActive = Color.DodgerBlue;
			tbmapb1.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbmapb1.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbmapb1.BorderColorIdle = Color.Silver;
			tbmapb1.BorderRadius = 1;
			tbmapb1.BorderThickness = 1;
			tbmapb1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbmapb1.CharacterCasing = CharacterCasing.Normal;
			tbmapb1.DefaultFont = new Font("Segoe UI", 9.25F);
			tbmapb1.DefaultText = "";
			tbmapb1.FillColor = Color.White;
			tbmapb1.HideSelection = true;
			tbmapb1.IconLeft = null;
			tbmapb1.IconLeftCursor = Cursors.IBeam;
			tbmapb1.IconPadding = 10;
			tbmapb1.IconRight = null;
			tbmapb1.IconRightCursor = Cursors.IBeam;
			tbmapb1.Location = new Point(204, 290);
			tbmapb1.MaxLength = 32767;
			tbmapb1.MinimumSize = new Size(1, 1);
			tbmapb1.Modified = false;
			tbmapb1.Multiline = false;
			tbmapb1.Name = "tbmapb1";
			stateProperties1.BorderColor = Color.DodgerBlue;
			stateProperties1.FillColor = Color.Empty;
			stateProperties1.ForeColor = Color.Empty;
			stateProperties1.PlaceholderForeColor = Color.Empty;
			tbmapb1.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties2.PlaceholderForeColor = Color.DarkGray;
			tbmapb1.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties3.FillColor = Color.Empty;
			stateProperties3.ForeColor = Color.Empty;
			stateProperties3.PlaceholderForeColor = Color.Empty;
			tbmapb1.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = Color.Silver;
			stateProperties4.FillColor = Color.White;
			stateProperties4.ForeColor = Color.Empty;
			stateProperties4.PlaceholderForeColor = Color.Empty;
			tbmapb1.OnIdleState = stateProperties4;
			tbmapb1.Padding = new Padding(3);
			tbmapb1.PasswordChar = '\0';
			tbmapb1.PlaceholderForeColor = Color.Silver;
			tbmapb1.PlaceholderText = "Enter text";
			tbmapb1.ReadOnly = false;
			tbmapb1.ScrollBars = ScrollBars.None;
			tbmapb1.SelectedText = "";
			tbmapb1.SelectionLength = 0;
			tbmapb1.SelectionStart = 0;
			tbmapb1.ShortcutsEnabled = true;
			tbmapb1.Size = new Size(102, 35);
			tbmapb1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbmapb1.TabIndex = 1;
			tbmapb1.TextAlign = HorizontalAlignment.Left;
			tbmapb1.TextMarginBottom = 0;
			tbmapb1.TextMarginLeft = 3;
			tbmapb1.TextMarginTop = 1;
			tbmapb1.TextPlaceholder = "Enter text";
			tbmapb1.UseSystemPasswordChar = false;
			tbmapb1.WordWrap = true;
			// 
			// bunifuLabel1
			// 
			bunifuLabel1.AllowParentOverrides = false;
			bunifuLabel1.AutoEllipsis = false;
			bunifuLabel1.CursorType = Cursors.Default;
			bunifuLabel1.Font = new Font("Segoe UI", 15F);
			bunifuLabel1.Location = new Point(72, 290);
			bunifuLabel1.Name = "bunifuLabel1";
			bunifuLabel1.RightToLeft = RightToLeft.No;
			bunifuLabel1.Size = new Size(114, 35);
			bunifuLabel1.TabIndex = 2;
			bunifuLabel1.Text = "Mã Phòng";
			bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// btthempb
			// 
			btthempb.AllowAnimations = true;
			btthempb.AllowMouseEffects = true;
			btthempb.AllowToggling = false;
			btthempb.AnimationSpeed = 200;
			btthempb.AutoGenerateColors = false;
			btthempb.AutoRoundBorders = false;
			btthempb.AutoSizeLeftIcon = true;
			btthempb.AutoSizeRightIcon = true;
			btthempb.BackColor = Color.Transparent;
			btthempb.BackColor1 = Color.FromArgb(51, 122, 183);
			btthempb.BackgroundImage = (Image)resources.GetObject("btthempb.BackgroundImage");
			btthempb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthempb.ButtonText = "Thêm";
			btthempb.ButtonTextMarginLeft = 0;
			btthempb.ColorContrastOnClick = 45;
			btthempb.ColorContrastOnHover = 45;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			btthempb.CustomizableEdges = borderEdges1;
			btthempb.DialogResult = DialogResult.None;
			btthempb.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btthempb.DisabledFillColor = Color.Empty;
			btthempb.DisabledForecolor = Color.Empty;
			btthempb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btthempb.Font = new Font("Segoe UI", 9F);
			btthempb.ForeColor = Color.White;
			btthempb.IconLeft = null;
			btthempb.IconLeftAlign = ContentAlignment.MiddleLeft;
			btthempb.IconLeftCursor = Cursors.Default;
			btthempb.IconLeftPadding = new Padding(11, 3, 3, 3);
			btthempb.IconMarginLeft = 11;
			btthempb.IconPadding = 10;
			btthempb.IconRight = null;
			btthempb.IconRightAlign = ContentAlignment.MiddleRight;
			btthempb.IconRightCursor = Cursors.Default;
			btthempb.IconRightPadding = new Padding(3, 3, 7, 3);
			btthempb.IconSize = 25;
			btthempb.IdleBorderColor = Color.Empty;
			btthempb.IdleBorderRadius = 0;
			btthempb.IdleBorderThickness = 0;
			btthempb.IdleFillColor = Color.Empty;
			btthempb.IdleIconLeftImage = null;
			btthempb.IdleIconRightImage = null;
			btthempb.IndicateFocus = false;
			btthempb.Location = new Point(53, 459);
			btthempb.Name = "btthempb";
			btthempb.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btthempb.OnDisabledState.BorderRadius = 1;
			btthempb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthempb.OnDisabledState.BorderThickness = 1;
			btthempb.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btthempb.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btthempb.OnDisabledState.IconLeftImage = null;
			btthempb.OnDisabledState.IconRightImage = null;
			btthempb.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btthempb.onHoverState.BorderRadius = 1;
			btthempb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthempb.onHoverState.BorderThickness = 1;
			btthempb.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btthempb.onHoverState.ForeColor = Color.White;
			btthempb.onHoverState.IconLeftImage = null;
			btthempb.onHoverState.IconRightImage = null;
			btthempb.OnIdleState.BorderColor = Color.DodgerBlue;
			btthempb.OnIdleState.BorderRadius = 1;
			btthempb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthempb.OnIdleState.BorderThickness = 1;
			btthempb.OnIdleState.FillColor = Color.DodgerBlue;
			btthempb.OnIdleState.ForeColor = Color.White;
			btthempb.OnIdleState.IconLeftImage = null;
			btthempb.OnIdleState.IconRightImage = null;
			btthempb.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btthempb.OnPressedState.BorderRadius = 1;
			btthempb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btthempb.OnPressedState.BorderThickness = 1;
			btthempb.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btthempb.OnPressedState.ForeColor = Color.White;
			btthempb.OnPressedState.IconLeftImage = null;
			btthempb.OnPressedState.IconRightImage = null;
			btthempb.Size = new Size(113, 49);
			btthempb.TabIndex = 3;
			btthempb.TextAlign = ContentAlignment.MiddleCenter;
			btthempb.TextAlignment = HorizontalAlignment.Center;
			btthempb.TextMarginLeft = 0;
			btthempb.TextPadding = new Padding(0);
			btthempb.UseDefaultRadiusAndThickness = true;
			btthempb.Click += btthempb_Click;
			// 
			// btnsuapb
			// 
			btnsuapb.AllowAnimations = true;
			btnsuapb.AllowMouseEffects = true;
			btnsuapb.AllowToggling = false;
			btnsuapb.AnimationSpeed = 200;
			btnsuapb.AutoGenerateColors = false;
			btnsuapb.AutoRoundBorders = false;
			btnsuapb.AutoSizeLeftIcon = true;
			btnsuapb.AutoSizeRightIcon = true;
			btnsuapb.BackColor = Color.Transparent;
			btnsuapb.BackColor1 = Color.FromArgb(51, 122, 183);
			btnsuapb.BackgroundImage = (Image)resources.GetObject("btnsuapb.BackgroundImage");
			btnsuapb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnsuapb.ButtonText = "Sửa";
			btnsuapb.ButtonTextMarginLeft = 0;
			btnsuapb.ColorContrastOnClick = 45;
			btnsuapb.ColorContrastOnHover = 45;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			btnsuapb.CustomizableEdges = borderEdges2;
			btnsuapb.DialogResult = DialogResult.None;
			btnsuapb.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btnsuapb.DisabledFillColor = Color.Empty;
			btnsuapb.DisabledForecolor = Color.Empty;
			btnsuapb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btnsuapb.Font = new Font("Segoe UI", 9F);
			btnsuapb.ForeColor = Color.White;
			btnsuapb.IconLeft = null;
			btnsuapb.IconLeftAlign = ContentAlignment.MiddleLeft;
			btnsuapb.IconLeftCursor = Cursors.Default;
			btnsuapb.IconLeftPadding = new Padding(11, 3, 3, 3);
			btnsuapb.IconMarginLeft = 11;
			btnsuapb.IconPadding = 10;
			btnsuapb.IconRight = null;
			btnsuapb.IconRightAlign = ContentAlignment.MiddleRight;
			btnsuapb.IconRightCursor = Cursors.Default;
			btnsuapb.IconRightPadding = new Padding(3, 3, 7, 3);
			btnsuapb.IconSize = 25;
			btnsuapb.IdleBorderColor = Color.Empty;
			btnsuapb.IdleBorderRadius = 0;
			btnsuapb.IdleBorderThickness = 0;
			btnsuapb.IdleFillColor = Color.Empty;
			btnsuapb.IdleIconLeftImage = null;
			btnsuapb.IdleIconRightImage = null;
			btnsuapb.IndicateFocus = false;
			btnsuapb.Location = new Point(193, 459);
			btnsuapb.Name = "btnsuapb";
			btnsuapb.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btnsuapb.OnDisabledState.BorderRadius = 1;
			btnsuapb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnsuapb.OnDisabledState.BorderThickness = 1;
			btnsuapb.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btnsuapb.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btnsuapb.OnDisabledState.IconLeftImage = null;
			btnsuapb.OnDisabledState.IconRightImage = null;
			btnsuapb.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btnsuapb.onHoverState.BorderRadius = 1;
			btnsuapb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnsuapb.onHoverState.BorderThickness = 1;
			btnsuapb.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btnsuapb.onHoverState.ForeColor = Color.White;
			btnsuapb.onHoverState.IconLeftImage = null;
			btnsuapb.onHoverState.IconRightImage = null;
			btnsuapb.OnIdleState.BorderColor = Color.DodgerBlue;
			btnsuapb.OnIdleState.BorderRadius = 1;
			btnsuapb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnsuapb.OnIdleState.BorderThickness = 1;
			btnsuapb.OnIdleState.FillColor = Color.DodgerBlue;
			btnsuapb.OnIdleState.ForeColor = Color.White;
			btnsuapb.OnIdleState.IconLeftImage = null;
			btnsuapb.OnIdleState.IconRightImage = null;
			btnsuapb.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btnsuapb.OnPressedState.BorderRadius = 1;
			btnsuapb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnsuapb.OnPressedState.BorderThickness = 1;
			btnsuapb.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btnsuapb.OnPressedState.ForeColor = Color.White;
			btnsuapb.OnPressedState.IconLeftImage = null;
			btnsuapb.OnPressedState.IconRightImage = null;
			btnsuapb.Size = new Size(113, 49);
			btnsuapb.TabIndex = 4;
			btnsuapb.TextAlign = ContentAlignment.MiddleCenter;
			btnsuapb.TextAlignment = HorizontalAlignment.Center;
			btnsuapb.TextMarginLeft = 0;
			btnsuapb.TextPadding = new Padding(0);
			btnsuapb.UseDefaultRadiusAndThickness = true;
			btnsuapb.Click += btnsuapb_Click;
			// 
			// btnxoapb
			// 
			btnxoapb.AllowAnimations = true;
			btnxoapb.AllowMouseEffects = true;
			btnxoapb.AllowToggling = false;
			btnxoapb.AnimationSpeed = 200;
			btnxoapb.AutoGenerateColors = false;
			btnxoapb.AutoRoundBorders = false;
			btnxoapb.AutoSizeLeftIcon = true;
			btnxoapb.AutoSizeRightIcon = true;
			btnxoapb.BackColor = Color.Transparent;
			btnxoapb.BackColor1 = Color.FromArgb(51, 122, 183);
			btnxoapb.BackgroundImage = (Image)resources.GetObject("btnxoapb.BackgroundImage");
			btnxoapb.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnxoapb.ButtonText = "Xóa";
			btnxoapb.ButtonTextMarginLeft = 0;
			btnxoapb.ColorContrastOnClick = 45;
			btnxoapb.ColorContrastOnHover = 45;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			btnxoapb.CustomizableEdges = borderEdges3;
			btnxoapb.DialogResult = DialogResult.None;
			btnxoapb.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btnxoapb.DisabledFillColor = Color.Empty;
			btnxoapb.DisabledForecolor = Color.Empty;
			btnxoapb.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btnxoapb.Font = new Font("Segoe UI", 9F);
			btnxoapb.ForeColor = Color.White;
			btnxoapb.IconLeft = null;
			btnxoapb.IconLeftAlign = ContentAlignment.MiddleLeft;
			btnxoapb.IconLeftCursor = Cursors.Default;
			btnxoapb.IconLeftPadding = new Padding(11, 3, 3, 3);
			btnxoapb.IconMarginLeft = 11;
			btnxoapb.IconPadding = 10;
			btnxoapb.IconRight = null;
			btnxoapb.IconRightAlign = ContentAlignment.MiddleRight;
			btnxoapb.IconRightCursor = Cursors.Default;
			btnxoapb.IconRightPadding = new Padding(3, 3, 7, 3);
			btnxoapb.IconSize = 25;
			btnxoapb.IdleBorderColor = Color.Empty;
			btnxoapb.IdleBorderRadius = 0;
			btnxoapb.IdleBorderThickness = 0;
			btnxoapb.IdleFillColor = Color.Empty;
			btnxoapb.IdleIconLeftImage = null;
			btnxoapb.IdleIconRightImage = null;
			btnxoapb.IndicateFocus = false;
			btnxoapb.Location = new Point(341, 459);
			btnxoapb.Name = "btnxoapb";
			btnxoapb.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btnxoapb.OnDisabledState.BorderRadius = 1;
			btnxoapb.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnxoapb.OnDisabledState.BorderThickness = 1;
			btnxoapb.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btnxoapb.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btnxoapb.OnDisabledState.IconLeftImage = null;
			btnxoapb.OnDisabledState.IconRightImage = null;
			btnxoapb.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btnxoapb.onHoverState.BorderRadius = 1;
			btnxoapb.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnxoapb.onHoverState.BorderThickness = 1;
			btnxoapb.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btnxoapb.onHoverState.ForeColor = Color.White;
			btnxoapb.onHoverState.IconLeftImage = null;
			btnxoapb.onHoverState.IconRightImage = null;
			btnxoapb.OnIdleState.BorderColor = Color.DodgerBlue;
			btnxoapb.OnIdleState.BorderRadius = 1;
			btnxoapb.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnxoapb.OnIdleState.BorderThickness = 1;
			btnxoapb.OnIdleState.FillColor = Color.DodgerBlue;
			btnxoapb.OnIdleState.ForeColor = Color.White;
			btnxoapb.OnIdleState.IconLeftImage = null;
			btnxoapb.OnIdleState.IconRightImage = null;
			btnxoapb.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btnxoapb.OnPressedState.BorderRadius = 1;
			btnxoapb.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnxoapb.OnPressedState.BorderThickness = 1;
			btnxoapb.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btnxoapb.OnPressedState.ForeColor = Color.White;
			btnxoapb.OnPressedState.IconLeftImage = null;
			btnxoapb.OnPressedState.IconRightImage = null;
			btnxoapb.Size = new Size(113, 49);
			btnxoapb.TabIndex = 5;
			btnxoapb.TextAlign = ContentAlignment.MiddleCenter;
			btnxoapb.TextAlignment = HorizontalAlignment.Center;
			btnxoapb.TextMarginLeft = 0;
			btnxoapb.TextPadding = new Padding(0);
			btnxoapb.UseDefaultRadiusAndThickness = true;
			btnxoapb.Click += btnxoapb_Click;
			// 
			// btnclear
			// 
			btnclear.AllowAnimations = true;
			btnclear.AllowMouseEffects = true;
			btnclear.AllowToggling = false;
			btnclear.AnimationSpeed = 200;
			btnclear.AutoGenerateColors = false;
			btnclear.AutoRoundBorders = false;
			btnclear.AutoSizeLeftIcon = true;
			btnclear.AutoSizeRightIcon = true;
			btnclear.BackColor = Color.Transparent;
			btnclear.BackColor1 = Color.FromArgb(51, 122, 183);
			btnclear.BackgroundImage = (Image)resources.GetObject("btnclear.BackgroundImage");
			btnclear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnclear.ButtonText = "Clear";
			btnclear.ButtonTextMarginLeft = 0;
			btnclear.ColorContrastOnClick = 45;
			btnclear.ColorContrastOnHover = 45;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			btnclear.CustomizableEdges = borderEdges4;
			btnclear.DialogResult = DialogResult.None;
			btnclear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			btnclear.DisabledFillColor = Color.Empty;
			btnclear.DisabledForecolor = Color.Empty;
			btnclear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			btnclear.Font = new Font("Segoe UI", 9F);
			btnclear.ForeColor = Color.White;
			btnclear.IconLeft = null;
			btnclear.IconLeftAlign = ContentAlignment.MiddleLeft;
			btnclear.IconLeftCursor = Cursors.Default;
			btnclear.IconLeftPadding = new Padding(11, 3, 3, 3);
			btnclear.IconMarginLeft = 11;
			btnclear.IconPadding = 10;
			btnclear.IconRight = null;
			btnclear.IconRightAlign = ContentAlignment.MiddleRight;
			btnclear.IconRightCursor = Cursors.Default;
			btnclear.IconRightPadding = new Padding(3, 3, 7, 3);
			btnclear.IconSize = 25;
			btnclear.IdleBorderColor = Color.Empty;
			btnclear.IdleBorderRadius = 0;
			btnclear.IdleBorderThickness = 0;
			btnclear.IdleFillColor = Color.Empty;
			btnclear.IdleIconLeftImage = null;
			btnclear.IdleIconRightImage = null;
			btnclear.IndicateFocus = false;
			btnclear.Location = new Point(490, 459);
			btnclear.Name = "btnclear";
			btnclear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			btnclear.OnDisabledState.BorderRadius = 1;
			btnclear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnclear.OnDisabledState.BorderThickness = 1;
			btnclear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			btnclear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			btnclear.OnDisabledState.IconLeftImage = null;
			btnclear.OnDisabledState.IconRightImage = null;
			btnclear.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			btnclear.onHoverState.BorderRadius = 1;
			btnclear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnclear.onHoverState.BorderThickness = 1;
			btnclear.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			btnclear.onHoverState.ForeColor = Color.White;
			btnclear.onHoverState.IconLeftImage = null;
			btnclear.onHoverState.IconRightImage = null;
			btnclear.OnIdleState.BorderColor = Color.DodgerBlue;
			btnclear.OnIdleState.BorderRadius = 1;
			btnclear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnclear.OnIdleState.BorderThickness = 1;
			btnclear.OnIdleState.FillColor = Color.DodgerBlue;
			btnclear.OnIdleState.ForeColor = Color.White;
			btnclear.OnIdleState.IconLeftImage = null;
			btnclear.OnIdleState.IconRightImage = null;
			btnclear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			btnclear.OnPressedState.BorderRadius = 1;
			btnclear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			btnclear.OnPressedState.BorderThickness = 1;
			btnclear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			btnclear.OnPressedState.ForeColor = Color.White;
			btnclear.OnPressedState.IconLeftImage = null;
			btnclear.OnPressedState.IconRightImage = null;
			btnclear.Size = new Size(113, 49);
			btnclear.TabIndex = 6;
			btnclear.TextAlign = ContentAlignment.MiddleCenter;
			btnclear.TextAlignment = HorizontalAlignment.Center;
			btnclear.TextMarginLeft = 0;
			btnclear.TextPadding = new Padding(0);
			btnclear.UseDefaultRadiusAndThickness = true;
			btnclear.Click += btnclear_Click;
			// 
			// bunifuButton5
			// 
			bunifuButton5.AllowAnimations = true;
			bunifuButton5.AllowMouseEffects = true;
			bunifuButton5.AllowToggling = false;
			bunifuButton5.AnimationSpeed = 200;
			bunifuButton5.AutoGenerateColors = false;
			bunifuButton5.AutoRoundBorders = false;
			bunifuButton5.AutoSizeLeftIcon = true;
			bunifuButton5.AutoSizeRightIcon = true;
			bunifuButton5.BackColor = Color.Transparent;
			bunifuButton5.BackColor1 = Color.FromArgb(51, 122, 183);
			bunifuButton5.BackgroundImage = (Image)resources.GetObject("bunifuButton5.BackgroundImage");
			bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.ButtonText = "Home";
			bunifuButton5.ButtonTextMarginLeft = 0;
			bunifuButton5.ColorContrastOnClick = 45;
			bunifuButton5.ColorContrastOnHover = 45;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			bunifuButton5.CustomizableEdges = borderEdges5;
			bunifuButton5.DialogResult = DialogResult.None;
			bunifuButton5.DisabledBorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.DisabledFillColor = Color.Empty;
			bunifuButton5.DisabledForecolor = Color.Empty;
			bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			bunifuButton5.Font = new Font("Segoe UI", 9F);
			bunifuButton5.ForeColor = Color.White;
			bunifuButton5.IconLeft = null;
			bunifuButton5.IconLeftAlign = ContentAlignment.MiddleLeft;
			bunifuButton5.IconLeftCursor = Cursors.Default;
			bunifuButton5.IconLeftPadding = new Padding(11, 3, 3, 3);
			bunifuButton5.IconMarginLeft = 11;
			bunifuButton5.IconPadding = 10;
			bunifuButton5.IconRight = null;
			bunifuButton5.IconRightAlign = ContentAlignment.MiddleRight;
			bunifuButton5.IconRightCursor = Cursors.Default;
			bunifuButton5.IconRightPadding = new Padding(3, 3, 7, 3);
			bunifuButton5.IconSize = 25;
			bunifuButton5.IdleBorderColor = Color.Empty;
			bunifuButton5.IdleBorderRadius = 0;
			bunifuButton5.IdleBorderThickness = 0;
			bunifuButton5.IdleFillColor = Color.Empty;
			bunifuButton5.IdleIconLeftImage = null;
			bunifuButton5.IdleIconRightImage = null;
			bunifuButton5.IndicateFocus = false;
			bunifuButton5.Location = new Point(640, 459);
			bunifuButton5.Name = "bunifuButton5";
			bunifuButton5.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
			bunifuButton5.OnDisabledState.BorderRadius = 1;
			bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnDisabledState.BorderThickness = 1;
			bunifuButton5.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
			bunifuButton5.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
			bunifuButton5.OnDisabledState.IconLeftImage = null;
			bunifuButton5.OnDisabledState.IconRightImage = null;
			bunifuButton5.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.BorderRadius = 1;
			bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.onHoverState.BorderThickness = 1;
			bunifuButton5.onHoverState.FillColor = Color.FromArgb(30, 150, 255);
			bunifuButton5.onHoverState.ForeColor = Color.White;
			bunifuButton5.onHoverState.IconLeftImage = null;
			bunifuButton5.onHoverState.IconRightImage = null;
			bunifuButton5.OnIdleState.BorderColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.BorderRadius = 1;
			bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnIdleState.BorderThickness = 1;
			bunifuButton5.OnIdleState.FillColor = Color.DodgerBlue;
			bunifuButton5.OnIdleState.ForeColor = Color.White;
			bunifuButton5.OnIdleState.IconLeftImage = null;
			bunifuButton5.OnIdleState.IconRightImage = null;
			bunifuButton5.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.BorderRadius = 1;
			bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			bunifuButton5.OnPressedState.BorderThickness = 1;
			bunifuButton5.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
			bunifuButton5.OnPressedState.ForeColor = Color.White;
			bunifuButton5.OnPressedState.IconLeftImage = null;
			bunifuButton5.OnPressedState.IconRightImage = null;
			bunifuButton5.Size = new Size(113, 49);
			bunifuButton5.TabIndex = 7;
			bunifuButton5.TextAlign = ContentAlignment.MiddleCenter;
			bunifuButton5.TextAlignment = HorizontalAlignment.Center;
			bunifuButton5.TextMarginLeft = 0;
			bunifuButton5.TextPadding = new Padding(0);
			bunifuButton5.UseDefaultRadiusAndThickness = true;
			bunifuButton5.Click += bunifuButton5_Click;
			// 
			// bunifuLabel2
			// 
			bunifuLabel2.AllowParentOverrides = false;
			bunifuLabel2.AutoEllipsis = false;
			bunifuLabel2.CursorType = Cursors.Default;
			bunifuLabel2.Font = new Font("Segoe UI", 15F);
			bunifuLabel2.Location = new Point(72, 357);
			bunifuLabel2.Name = "bunifuLabel2";
			bunifuLabel2.RightToLeft = RightToLeft.No;
			bunifuLabel2.Size = new Size(119, 35);
			bunifuLabel2.TabIndex = 9;
			bunifuLabel2.Text = "Tên Phòng";
			bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbtenpb2
			// 
			tbtenpb2.AcceptsReturn = false;
			tbtenpb2.AcceptsTab = false;
			tbtenpb2.AnimationSpeed = 200;
			tbtenpb2.AutoCompleteMode = AutoCompleteMode.None;
			tbtenpb2.AutoCompleteSource = AutoCompleteSource.None;
			tbtenpb2.AutoSizeHeight = true;
			tbtenpb2.BackColor = Color.Transparent;
			tbtenpb2.BackgroundImage = (Image)resources.GetObject("tbtenpb2.BackgroundImage");
			tbtenpb2.BorderColorActive = Color.DodgerBlue;
			tbtenpb2.BorderColorDisabled = Color.FromArgb(204, 204, 204);
			tbtenpb2.BorderColorHover = Color.FromArgb(105, 181, 255);
			tbtenpb2.BorderColorIdle = Color.Silver;
			tbtenpb2.BorderRadius = 1;
			tbtenpb2.BorderThickness = 1;
			tbtenpb2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			tbtenpb2.CharacterCasing = CharacterCasing.Normal;
			tbtenpb2.DefaultFont = new Font("Segoe UI", 9.25F);
			tbtenpb2.DefaultText = "";
			tbtenpb2.FillColor = Color.White;
			tbtenpb2.HideSelection = true;
			tbtenpb2.IconLeft = null;
			tbtenpb2.IconLeftCursor = Cursors.IBeam;
			tbtenpb2.IconPadding = 10;
			tbtenpb2.IconRight = null;
			tbtenpb2.IconRightCursor = Cursors.IBeam;
			tbtenpb2.Location = new Point(204, 357);
			tbtenpb2.MaxLength = 32767;
			tbtenpb2.MinimumSize = new Size(1, 1);
			tbtenpb2.Modified = false;
			tbtenpb2.Multiline = false;
			tbtenpb2.Name = "tbtenpb2";
			stateProperties5.BorderColor = Color.DodgerBlue;
			stateProperties5.FillColor = Color.Empty;
			stateProperties5.ForeColor = Color.Empty;
			stateProperties5.PlaceholderForeColor = Color.Empty;
			tbtenpb2.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
			stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
			stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
			stateProperties6.PlaceholderForeColor = Color.DarkGray;
			tbtenpb2.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
			stateProperties7.FillColor = Color.Empty;
			stateProperties7.ForeColor = Color.Empty;
			stateProperties7.PlaceholderForeColor = Color.Empty;
			tbtenpb2.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = Color.Silver;
			stateProperties8.FillColor = Color.White;
			stateProperties8.ForeColor = Color.Empty;
			stateProperties8.PlaceholderForeColor = Color.Empty;
			tbtenpb2.OnIdleState = stateProperties8;
			tbtenpb2.Padding = new Padding(3);
			tbtenpb2.PasswordChar = '\0';
			tbtenpb2.PlaceholderForeColor = Color.Silver;
			tbtenpb2.PlaceholderText = "Enter text";
			tbtenpb2.ReadOnly = false;
			tbtenpb2.ScrollBars = ScrollBars.None;
			tbtenpb2.SelectedText = "";
			tbtenpb2.SelectionLength = 0;
			tbtenpb2.SelectionStart = 0;
			tbtenpb2.ShortcutsEnabled = true;
			tbtenpb2.Size = new Size(102, 35);
			tbtenpb2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			tbtenpb2.TabIndex = 8;
			tbtenpb2.TextAlign = HorizontalAlignment.Left;
			tbtenpb2.TextMarginBottom = 0;
			tbtenpb2.TextMarginLeft = 3;
			tbtenpb2.TextMarginTop = 1;
			tbtenpb2.TextPlaceholder = "Enter text";
			tbtenpb2.UseSystemPasswordChar = false;
			tbtenpb2.WordWrap = true;
			// 
			// bunifuLabel3
			// 
			bunifuLabel3.AllowParentOverrides = false;
			bunifuLabel3.AutoEllipsis = false;
			bunifuLabel3.CursorType = Cursors.Default;
			bunifuLabel3.Font = new Font("Segoe UI", 15F);
			bunifuLabel3.Location = new Point(377, 290);
			bunifuLabel3.Name = "bunifuLabel3";
			bunifuLabel3.RightToLeft = RightToLeft.No;
			bunifuLabel3.Size = new Size(160, 35);
			bunifuLabel3.TabIndex = 11;
			bunifuLabel3.Text = "Trưởng Phòng";
			bunifuLabel3.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// bunifuLabel4
			// 
			bunifuLabel4.AllowParentOverrides = false;
			bunifuLabel4.AutoEllipsis = false;
			bunifuLabel4.CursorType = Cursors.Default;
			bunifuLabel4.Font = new Font("Segoe UI", 15F);
			bunifuLabel4.Location = new Point(377, 357);
			bunifuLabel4.Name = "bunifuLabel4";
			bunifuLabel4.RightToLeft = RightToLeft.No;
			bunifuLabel4.Size = new Size(68, 35);
			bunifuLabel4.TabIndex = 13;
			bunifuLabel4.Text = "Đề Án";
			bunifuLabel4.TextAlignment = ContentAlignment.TopLeft;
			bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
			// 
			// tbtentp3
			// 
			tbtentp3.FormattingEnabled = true;
			tbtentp3.Location = new Point(606, 297);
			tbtentp3.Name = "tbtentp3";
			tbtentp3.Size = new Size(106, 28);
			tbtentp3.TabIndex = 14;
			tbtentp3.KeyPress += tbtentp3_KeyPress;
			// 
			// tbmada4
			// 
			tbmada4.FormattingEnabled = true;
			tbmada4.Location = new Point(606, 364);
			tbmada4.Name = "tbmada4";
			tbmada4.Size = new Size(106, 28);
			tbmada4.TabIndex = 15;
			tbmada4.KeyPress += tbmada4_KeyPress;
			// 
			// PhongBan
			// 
			AutoScaleDimensions = new SizeF(8F, 20F);
			AutoScaleMode = AutoScaleMode.Font;
			ClientSize = new Size(794, 565);
			Controls.Add(tbmada4);
			Controls.Add(tbtentp3);
			Controls.Add(bunifuLabel4);
			Controls.Add(bunifuLabel3);
			Controls.Add(bunifuLabel2);
			Controls.Add(tbtenpb2);
			Controls.Add(bunifuButton5);
			Controls.Add(btnclear);
			Controls.Add(btnxoapb);
			Controls.Add(btnsuapb);
			Controls.Add(btthempb);
			Controls.Add(bunifuLabel1);
			Controls.Add(tbmapb1);
			Controls.Add(bunifuGroupBox1);
			Name = "PhongBan";
			Text = "PhongBan";
			Load += PhongBan_Load;
			bunifuGroupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)dtgpb).EndInit();
			ResumeLayout(false);
			PerformLayout();
		}

		#endregion

		private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
		private Bunifu.UI.WinForms.BunifuDataGridView dtgpb;
		private Bunifu.UI.WinForms.BunifuTextBox tbmapb1;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btthempb;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsuapb;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnxoapb;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnclear;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
		private Bunifu.UI.WinForms.BunifuTextBox tbtenpb2;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
		private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
		private ComboBox tbtentp3;
		private ComboBox tbmada4;
	}
}